---
monit_version: 1:5.6-2
monit_slack_channel: mum_infra_alerts
monit_slack_user: Prod_monit
monit_slack_webhook_url: https://hooks.slack.com/services/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

# Override values based on templates starting with check_
monit_checks: []