- name: Ensure {{ ci_proxy_nginx_ssl_dir }} exists
  file: path={{ ci_proxy_nginx_ssl_dir }} state=directory
  notify: restart nginx

- name: Ensure {{ ci_proxy_nginx_ssl_cert_file }} exists
  copy: dest={{ ci_proxy_nginx_ssl_cert_file }} content={{ vault_ci_proxy_nginx_ssl_cert }}  mode=0600
  notify: restart nginx

- name: Ensure {{ ci_proxy_nginx_ssl_key_file }} exists
  copy: dest={{ ci_proxy_nginx_ssl_key_file }} content={{ vault_ci_proxy_nginx_ssl_key }} mode=0600
  notify: restart nginx
