apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apimanager-vs
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  - public-gateway
  hosts:
  - {{ .Values.domain_name }} 
  http:
  - match:
    - uri:
        prefix: /api/
    rewrite:
      uri: /
    route:
    - destination:
        host: kong
        port:
          number: 8000
  - match:
    - uri:
        prefix: /action/data/v3/metrics/
    rewrite:
      uri: /data/v3/metrics/
    route:
    - destination:
        host: kong
        port:
          number: 8000
