apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ .Values.namespace }}-blob
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ .Values.cloud_storage_url }}
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: blob
    protocol: HTTP
  resolution: DNS

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}-keycloak
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.keycloak_ip }}

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ .Values.namespace }}-keycloak
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - keycloak.{{ .Values.namespace }}.{{ .Values.internal_domain_name | default "global" }}
  ports:
  - number: 8080
    name: keycloak
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
  - address: {{ .Values.keycloak_ip }}

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: swarm-grafana
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
  - address: {{ .Values.swarm_manager_ip }}
  hosts:
  - grafana.{{ .Values.namespace }}.global
  location: MESH_INTERNAL
  ports:
  - name: grafana
    number: 3001
    protocol: HTTP
  resolution: STATIC

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: swarm-kibana
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
  - address: {{ .Values.swarm_manager_ip }}
  hosts:
  - kibana.{{ .Values.namespace }}.global
  location: MESH_INTERNAL
  ports:
  - name: kibana
    number: 5601
    protocol: HTTP
  resolution: STATIC