version: '3'

services:
  kong:
    image: kong:0.10
    environment:
      KONG_CASSANDRA_CONTACT_POINTS: cassandra01
      KONG_LOG_LEVEL: error
      KONG_DATABASE: cassandra
    ports:
      - 8000
      - 8443
      - 8001
    deploy:
      replicas: 1