version: '3'

services:
  cassandra:
    image: cassandra:3.11.0
    volumes:
      - cassandra:/var/lib/cassandra
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.cassandra==1

  kong:
    image: kong:0.10.3
    environment:
      KONG_CASSANDRA_CONTACT_POINTS: api-manager_cassandra
      KONG_LOG_LEVEL: info
      KONG_DATABASE: cassandra
    ports:
      - 8000:8000
      - 8001:8001
    deploy:
      replicas: 1

volumes:
  cassandra:
    driver: local

networks:
  application_default:
    external: true
