---
kong_desktop_device_consumer_names_for_opa: '["desktop"]'
core_vault_sunbird_keycloak_user_federation_provider_id: "5bb6c87c-7c88-4d2b-af7e-534a2fef978d"
common_opa_policy_files:
  - main.rego
  - common.rego
service_opa_policy_files:
  - policies.rego
  - tests.rego
opa_policies_path: ../../../opa
common_opa_policies_path: "{{ opa_policies_path }}/common"