---
- name: install dependencies
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - conntrack

- name: install prometheus-node-exporter
  apt:
    name: prometheus-node-exporter
    state: present

- name: /etc/default/prometheus-node-exporter
  template:
    dest: /etc/default/prometheus-node-exporter
    src: prometheus-node-exporter.j2
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus-node-exporter

- name: start and enable the prometheus-node-exporter service
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

# - name: copy file_sd_config to prometheus hosts
#   template:
#     dest: "{{ item.path }}"
#     src: file_sd_config.yml.j2
#     owner: root
#     group: root
#     mode: 0644
#   delegate_to: "{{ item.host }}"
#   with_items: "{{ prometheus_node_exporter_file_sd_locations }}"
#   when: prometheus_node_exporter_file_sd
