actions:
  1:
    action: delete_snapshots
    description: Delete snapshots older than {{ es_snapshot_retention_days }} days
    options:
      repository: {{ es_snapshot_repository }}
    filters:
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: {{ es_snapshot_retention_days }}
