version: '3.3'

services:
  proxy:
    image: "{{hub_org}}/{{image_name}}:{{image_tag}}"
    ports:
      - "443:443"
      - "80:80"
    deploy:
      replicas: {{ proxy.replicas | default(1) }}
      resources:
        reservations:
          memory: "{{ proxy.reservation_memory | default('32M') }}"
        limits:
          memory: "{{ proxy.limit_memory | default('128M') }}"
      update_config:
        parallelism: 1
        delay: 30s
    secrets:
      - site.key
      - site.crt
      - prom_admin_creds
    configs:
      - source: proxy-default.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - default
      - api-manager_default
      - jenkins_default
      - monitor
      - {{ sunbird_network }}
      - logger
      - monitoring

secrets:
  site.key:
    external: true
  site.crt:
    external: true
  prom_admin_creds:
    external: true

configs:
  proxy-default.conf:
    external: true

networks:
  api-manager_default:
    external: true
  jenkins_default:
    external: true
  monitor:
    external: true
  {{ sunbird_network }}:
    external: true
  logger:
    external: true
  monitoring:
    external: true
  default:
    driver: overlay
