version: '3.3'

services:
  proxy:
    image: "{{hub_org}}/{{image_name}}:{{image_tag}}"
    ports:
      - "443:443"
      - "80:80"
      - "500:500"
    deploy:
      replicas: 1
    secrets:
      - site.key
      - site.crt
    configs:
      - source: proxy-default.conf
        target: /etc/nginx/default.conf
    networks:
      - default
      - api-manager_default
      - jenkins_default
      - monitor
      - {{ sunbird_network }}
      - logger_logger
      - monitoring

secrets:
  site.key:
    external: true
  site.crt:
    external: true

configs:
  proxy-default.conf:
    external: true

networks:
  api-manager_default:
    external: true
  jenkins_default:
    external: true
  monitor:
    external: true
  {{ sunbird_network }}:
    external: true
  logger_logger:
    external: true
  monitoring:
    external: true
  default:
    driver: overlay
