apiVersion: v1
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;

      location /learner/ {
        rewrite ^/learner/(.*) /$1 break;
        proxy_pass http://learner-service:9000;
      }
      location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://apimanager-service:8000;
      }
      location /admin-api/ {
        rewrite ^/admin-api/(.*) /$1 break;
        proxy_pass http://apimanager-service:8001;
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: private-ingress.conf
  namespace: {{ .Values.namespace }}
