apiVersion: v1
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;

      resolver {{ .Values.kube_dns_ip }};

      location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://kong:8000;
      }
      location /grafana/ {
        rewrite ^/grafana/(.*) /$1 break;
        proxy_pass http://prometheus-operator-grafana.monitoring.svc.cluster.local;
      }
      location /admin-api/ {
        rewrite ^/admin-api/(.*) /$1 break;
        proxy_pass http://kong:8001;
      }
      location /cert/ {
        rewrite ^/cert/(.*) /$1 break;
        proxy_pass http://cert-service:9000;
      }
      location /certreg/ {
        rewrite ^/certreg/(.*) /$1 break;
        proxy_pass http://cert-registry-service:9000;
      }
    }
kind: ConfigMap
metadata:
  name: nginx-private-ingress.conf
  namespace: {{ .Values.namespace }}
