postgresql_master_host: "{{ groups['postgresql-master'][0] }}"
postgresql_port: 5432
postgres_replication_user_name: replication
postgres_replication_user_password: "{{ vault_postgres_replication_user_password }}"
postgres_slave_to_master_trigger_file: /tmp/postgresql.trigger.{{ postgresql_port }}
postgresql_archive_dir: "{{ postgresql_data_dir }}/archive"
