# - name: Copy the templates
#   become: yes
#   template: src=curl_commands.j2 dest=/home/deployer/curl_commands.sh
             
# - name: Run the curl command
#   become: yes
#   shell: sh curl_commands.sh
#   args:
#     chdir: /home/deployer/

#     
- name: post to consul
  shell: curl -X POST \
  https://{{curl_host}}/api//user/v1/create \
  -H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2NTU0NDQ5ZWI0MGQ0YTI4ODQ3YzAzYWZlNmJjMmEyOCJ9.YhnTaDw_xvf8Q5S66QiO71-5WeqLaTPv-vvNZSwBqLk' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 6f643120-0807-28bb-08c3-91d11e316037' \
  -H 'ts: 2017-05-25 10:18:56:578+0530' \
  -H 'x-authenticated-userid: e9280b815c0e41972bf754e9409b66d778b8e11bb91844892869a1e828d7d2f2a' \
  -H 'x-consumer-id: X-Consumer-ID' \
  -H 'x-device-id: X-Device-ID' \
  -H 'x-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf' \
  -d '
{
 "params": { },
    "request":{                 
      "firstName": "apiuser868",
      "lastName": "Kumar",
      "password": "password",
      "provider":"NTP",
      "emailVerified": true,
      "phoneVerified": true,
      "email": "apiuse200@test.com",
          "userName":"apiuser200",
      "phone": "99000321212",
      "gender": "male",
      
      "avatar": null,
      "dob": "1992-10-12",
      "language":["English","Hindi"],
      "subject":["Physics","Math","English"],
      "address": [
        {
          "addType": "permanent",
          "addressLine1": "212 winding hill dr",
          "addressLine2": "Frazer town",
          "city": "Bangalore",
          "state": "Karnataka",
          "zipCode": "560103"
        } ,
        {
          "addType": "permanent",
          "addressLine1": "2121 winding hill dr",
          "addressLine2": "Frazer town1",
          "city": "Bangalore1",
          "state": "Karnataka1",
          "zipCode": "560135"
        } 
      ],
      "education": [
        {
          "degree": "Bachelor of Science",
          "yearOfPassing": 2012,
          "percentage": 72.5,
          "grade": "B",
          "name": "MG College",
          "boardOrUniversity": "Anna University",
          "address":{
                  "addressLine1": "2121 winding hill dr",
          "addressLine2": "Frazer town1",
          "city": "Bangalore1",
          "state": "Karnataka1",
          "zipCode": "560135"
          }
        },
        {
          "degree": "Plus 2",
          "yearOfPassing": 2009,
         
          "name": "Delhi Public School",
          "boardOrUniversity": "CBSE",
           "address":{
                  "addressLine1": "2121 winding hill dr",
          "addressLine2": "Frazer town1",
          "city": "Bangalore1",
          "state": "Karnataka1",
          "zipCode": "560135"
          }
        }
      ],
          "jobProfile":[
             {
                 "jobName":"jobName",
                 "role":"teacher",
                 "joiningDate":"1992-10-12",
                 "endDate":"1992-10-12",
                 
                 "orgName":"AP ORG",
                 "subject":["Physics","Chemistry"],
                
                "address":{
                  "addressLine1": "2121 winding hill dr",
          "addressLine2": "Frazer town1",
          "city": "Bangalore1",
          "state": "Karnataka1",
          "zipCode": "560135"
          }
                 },
                 {
                 "jobName":"jobName1",
                 "role":"teacher",
                 "joiningDate":"1992-10-12",
                 "endDate":"1992-10-12",
                 
                 "orgName":"AP ORG",
                 "subject":["Physics","Chemistry"],
                
                "address":{
                  "addressLine1": "2121 winding hill dr",
          "addressLine2": "Frazer town1",
          "city": "Bangalore1",
          "state": "Karnataka1",
          "zipCode": "560135"
          }
                 }
          ]
    }
}' 
