version: '3.1'

services:

  documentation-jenkins-slave:
    image: sunbird/documentation-jenkins-swarm-agent:0.0.1
    env_file:
      /home/deployer/env/api-manager.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      replicas: 1
    networks:
      - jenkins_default

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

networks:
  jenkins_default:
    external: true
