version: '3.1'

services:

  jenkins-slave:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://jenkins:8080/jenkins -labels 'docker' -executors 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
    secrets:
      - jenkins-user
      - jenkins-pass
      - hub-pass
      - deployer-ssh-key
      - source: deployer-ssh-key
        target: deployer-ssh-key
        mode: 0600

    deploy:
      mode: global
    networks:
      - jenkins_default

  api-manager-jenkins-slave:
    image: sunbird/api-manager-jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://jenkins:8080/jenkins -labels 'kong-api' -executors 1 -name api-manager-jenkins-slave
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      replicas: 1
    networks:
      - jenkins_default
      - api-manager_default

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
  hub-pass:
    external: true
  deployer-ssh-key:
    external: true

networks:
  jenkins_default:
    external: true
  api-manager_default:
    external: true
