version: '3.1'

services:

  jenkins:
    image: jenkinsci/jenkins:lts-alpine
    ports:
      - "50000:50000"
      - "8080:8080"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - jenkins:/var/jenkins_home
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080
      placement:
        constraints:
          - "node.labels.jenkins==1"
    networks:
      - jenkins

  jenkins-slave:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://jenkins/jenkins -labels 'docker' -executors 5 -disableSslVerification
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
    secrets:
      - jenkins-user
      - jenkins-pass
    networks:
      - jenkins

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jenkins:
    driver: local

networks:
  jenkins:
    driver: overlay

# docker service create --name jenkins \
#     -p 8082:8080 \
#     -p 50000:51000 \
#     -e JENKINS_OPTS="--prefix=/jenkins" \
#     --reserve-memory 300m \
#     --constraint "node.labels.build.role==master" \
#     --mount type=volume,volume-driver=local,source={{.Service.Name}}-{{.Task.Slot}}-vol,destination=/var/jenkins_home \
#     jenkinsci/jenkins:lts-alpine
