version: '3.1'

services:

  jenkins-slave:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://jenkins:8080/jenkins -labels 'docker' -executors 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      mode: global
    networks:
      - jenkins_default

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

networks:
  jenkins_default:
    external: true