version: "3.3"
services:
  opensaber-service:
    image: "{{hub_org}}/{{image_name}}:{{image_tag}}"
    deploy:
      replicas: 1
      placement:
          constraints:
            - "node.labels.opensaber==1"
      resources:
          reservations:
            memory: "{{ opensaber_reservation_memory }}"
          limits:
            memory: "{{ opensaber_limit_memory }}"
    configs:
      - source: opensaber_audit_frame.json
        target: /home/opensaber/config/audit_frame.json
      - source: opensaber_frame.json
        target: /home/opensaber/config/frame.json
      - source: opensaber_schema-configuration.jsonld
        target: /home/opensaber/config/schema-configuration.jsonld
      - source: opensaber_validations_create.shex
        target: /home/opensaber/config/validations_create.shex
      - source: opensaber_validations_update.shex
        target: /home/opensaber/config/validations_update.shex
    volumes:
      - /var/dockerdata/opensaber/data/:/data
      - /var/dockerdata/opensaber/logs:/logs
    env_file:
      /home/deployer/stack/opensaber.env
    networks:
      - application_default

networks:
  application_default:
    external: true

configs:
  opensaber_audit_frame.json:
    external: true
  opensaber_frame.json:
    external: true
  opensaber_schema-configuration.jsonld:
    external: true
  opensaber_validations_create.shex:
    external: true
  opensaber_validations_update.shex:
    external: true
