- name: copy the artifacts 
  copy: src=keycloak.tar.gz dest=/opt/  

- name: extarct the folder 
  unarchive: src=/opt/keycloak.tar.gz dest=/opt/ copy=no owner=keycloak group=keycloak

- name: remove files inside 
  file: path=/opt/keycloak/themes/sunrise/login/resources/{{item}} state=absent
  with_items:
             - css
             - img

- name: copy the artifacts 
  copy: src=artifacts/{{project}}/{{item}} dest=/opt/keycloak/themes/sunrise/login/resources/ owner=keycloak group=keycloak
  with_items: 
             - css
             - img

- name: copy login.ftl file
  copy: src=artifacts/{{project}}/{{item}} dest=/opt/keycloak/themes/sunrise/login/ owner=keycloak group=keycloak
  with_items: 
             - login.ftl
             - login-reset-password.ftl
             - login-update-password.ftl
             - theme.properties
             - messages
  


  

