---
# tasks file for keycloak

- name: Create driver directory
  file:
    path: /opt/keycloak/modules/system/layers/keycloak/org/postgresql/main
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 750
    state: directory

- name: Download driver
  get_url:
    url: https://jdbc.postgresql.org/download/postgresql-9.4.1212.jar
    dest: /opt/keycloak/modules/system/layers/keycloak/org/postgresql/main
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0750

- name: Copy module.xml
  template:
    src: module.xml.j2
    dest: "/opt/keycloak/modules/system/layers/keycloak/org/postgresql/main/module.xml"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0750

