---

# - name: status service 
#   become: yes
#   command: /etc/init.d/keycloak status
#   register: keycloak
#   ignore_errors: true

# - name: stop service 
#   become: yes
#   command: /etc/init.d/keycloak stop
#   when: "keycloak.stdout.find('running') != -1"
#   ignore_errors: true

# - name: start service 
#   become: yes
#   command: /etc/init.d/keycloak start
#   ignore_errors: true

- name: Create management user
  command: "{{ wildfly_dir }}/bin/add-user-keycloak.sh -r master -u {{ keycloak_management_user }} -p {{ keycloak_management_password }}"
  become_user: "{{ wildfly_user }}"
  when: keycloak_management_user is defined and
        keycloak_management_password is defined
  ignore_errors: yes