- name: copy the artifacts 
  copy: src=keycloak.tar.gz dest=/opt/  

- name: extarct the folder 
  unarchive: src=/opt/keycloak.tar.gz dest=/opt/ copy=no owner=keycloak group=keycloak


- name: copy the artifacts 
  copy: src=artifacts/sunbird/{{item}} dest=/opt/keycloak/themes/sunrise/login/resources/ owner=keycloak group=keycloak
  with_items: 
             - css
             - img

