# ---
# # tasks file for keycloak

- name: Check keycloak installation
  stat: path={{ wildfly_dir }}/bin/keycloak-install.cli
  register: keycloak_installation
  changed_when: not keycloak_installation.stat.exists

- name: Download keycloak tar file
  get_url: dest={{ keycloak_download_dir }} url={{ keycloak_download_url }}
  when: not keycloak_installation.stat.exists

- name: Unarchive downloaded file
  unarchive: src={{ keycloak_download_dir }}/{{ keycloak_download_file }}
             dest={{ keycloak_download_dir }} copy=no mode=0750
             owner={{ wildfly_user }} group={{ wildfly_group }}
  when: not keycloak_installation.stat.exists
 
- name: remove keycloak
  command: rm -rf /opt/keycloak

- name: rename the file
  command: creates="/opt/keycloak" mv /opt/keycloak-3.2.0.Final /opt/keycloak

#- name: copying the sunrise login logo
#  copy: src={{ theme }} dest={{ dest_theme }} owner={{ wildfly_user }} group={{ wildfly_group }}

#- name: Unarchive theme 
#  unarchive: src={{ dest_theme }}/sunrise.tar.gz dest=/opt/keycloak/themes/ owner={{ wildfly_user }} group={{ wildfly_group }}
