- include: deploy.yml
  tags:
    - deploy  

- include: configure.yml
  tags:
    - deploy

- include: driver.yml
  when: keycloak_ds_driver_url and
        keycloak_ds_driver_name and
        keycloak_ds_driver_module and
        keycloak_custom_driver
  tags:
    - deploy      

- include: users.yml
  tags:
    - deploy

- include: service.yml
  tags:
    - provision
