---
# tasks file for keycloak

#- include: install.yml
- include: configure.yml
  tags:
    - deployment

- include: driver.yml
  when: keycloak_ds_driver_url and
        keycloak_ds_driver_name and
        keycloak_ds_driver_module and
        keycloak_custom_driver
  tags:
    -deployment      
#- include: datasource.yml
#  when: keycloak_custom_ds != ""

- include: users.yml
  tags:
    - deployment

- include: service.yml
  tags:
    - provision
