
- name: status service 
  become: yes
  command: /etc/init.d/keycloak status
  register: keycloak
  ignore_errors: yes
  tags:
    - deploy  
       
  
- name: stop service 
  become: yes
  command: /etc/init.d/keycloak stop
  when: "keycloak.stdout.find('running') != -1"
  ignore_errors: yes
  tags:
    - deploy      
 
- include: deploy.yml
  tags:
    - deploy  

- include: configure.yml
  tags:
    - deploy

- include: driver.yml
  when: keycloak_ds_driver_url and
        keycloak_ds_driver_name and
        keycloak_ds_driver_module and
        keycloak_custom_driver
  tags:
    - deploy      

- include: users.yml
  tags:
    - deploy

- include: service.yml
  tags:
    - provision

- name: start service 
  become: yes
  command: /etc/init.d/keycloak start
  tags:
    - deploy      
  