- include: configure.yml
  tags:
    - provision

- include: driver.yml
  when: keycloak_ds_driver_url and
        keycloak_ds_driver_name and
        keycloak_ds_driver_module and
        keycloak_custom_driver
  tags:
    - provision      

- include: users.yml
  tags:
    - provision

- include: service.yml
  tags:
    - provision
