---
- name: Copy service file to init.d
  template: src=keycloak-service.j2 dest=/etc/init.d/keycloak mode=0755
  tags:
    - provision

- name: start service 
  become: yes
  command: /etc/init.d/keycloak status
  register: keycloak

- name: stop service 
  become: yes
  command: /etc/init.d/keycloak stop
  when: "keycloak.stdout.find('running') != -1"

- name: start service 
  become: yes
  command: /etc/init.d/keycloak start