- name: Add ES repo
  apt_repository: repo='deb [arch=amd64] http://packages.elastic.co/curator/5/debian9 stable main' state=present update_cache=yes

- name: Install elasticsearch curator
  apt: 
    name: elasticsearch-curator=3.4.1-1

- debug: msg='[{"filtertype":"age","source":"creation_date","direction":"older","unit":"days","unit_count":{{logger_log_retention_days}}},{"filtertype":"pattern","kind":"prefix","value":"logstash"}]'

- name: Delete old indices 
  shell: curator_cli --dry-run delete_indices --filter_list '[{"filtertype":"age","source":"creation_date","direction":"older","unit":"days","unit_count":45},{"filtertype":"pattern","kind":"prefix","value":"logstash"}]'