- name: update_cache
  become: yes
  apt: update_cache=yes

- name: start_mongod
  become: yes
  service: name=mongod state=started

- name: stop_mongod
  become: yes
  service: name=mongod state=stopped

- name: restart_mongod
  become: yes
  service: name=mongod state=restarted