snapshot_create_request_body: {
    type: azure,
    settings: {
      container: "elasticsearch-snapshots",
      base_path: "{{ snapshot_base_path }}"
    }
}

es_snapshot_host: "{{ groups['log-es-backup'][0] }}"
snapshot_base_path: logger
