snapshot_create_request_body: {
    type: azure,
    settings: {
      container: "{{ es_azure_backup_folder_name }}",
      base_path: "{{ snapshot_base_path }}_{{ base_path_date }}"
    }
}

# Override these values
es_snapshot_host: "localhost"
snapshot_base_path: "default"

azure_management_storage_account_name: "{{ sunbird_management_storage_account }}"
azure_management_storage_resource_group_name: "{{ azure_management_storage_resource_group_name }}"
es_azure_backup_folder_name: "elasticsearch-snapshots"