version: '3'

services:
  kong:
    image: sunbird/kong:0.9.9
    env_file:
      /home/deployer/env/api-manager.env
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - api-manager_default
      - "{{ sunbird_network }}"
    deploy:
      replicas: {{ kong.replicas | default(1) }}
      resources:
        reservations:
          memory: "{{ kong.reservation_memory | default('64M') }}"
        limits:
          memory: "{{ kong.limit_memory | default('256M') }}"
      update_config:
        parallelism: 1
        delay: 30s
    healthcheck:
      test: curl -f http://localhost:8001/status || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

  echo:
    image: "{{hub_org}}/{{echo_server_image_name}}:{{echo_server_image_tag}}"
    networks:
      - api-manager_default
    ports:
      - 9595:9595
    deploy:
      replicas: {{ echo_service.replicas | default(1) }}
      resources:
        reservations:
          memory: "{{ echo_service.reservation_memory | default('8M') }}"
        limits:
          memory: "{{ echo_service.limit_memory | default('16M') }}"
      update_config:
        parallelism: 1
        delay: 5s
    healthcheck:
      test: wget -q -s http://localhost:9595/hello || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  api-manager_default:
    external: true
  {{ sunbird_network }}:
    external: true
