version: '3'

services:
  kong:
    image: kong:0.9.9
    env_file:
      /home/deployer/env/api-manager.env
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - default
      - "{{ sunbird_network }}"
    deploy:
      replicas: 1

  echo:
    image: sunbird/echo-server:0.0.1-bronze
    networks:
      - default
    deploy:
      replicas: 1

volumes:
  pgdata:
    driver: local

networks:
  {{ sunbird_network }}:
    external: true
