version: '3'

services:
  kong:
    image: sunbird/kong:0.0.1-bronze
    env_file:
      /home/deployer/env/api-manager.env
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - api-manager_default
      - "{{ sunbird_network }}"
    deploy:
      replicas: 1

  echo:
    image: "{{hub_org}}/{{echo_server_image_name}}:{{echo_server_image_tag}}"
    networks:
      - api-manager_default
    ports:
      - 9595:9595
    deploy:
      replicas: 1

volumes:
  pgdata:
    driver: local

networks:
  api-manager_default:
    external: true
  {{ sunbird_network }}:
    external: true
