version: '3'

services:
  postgres:
    image: postgres:9.6.3
    env_file:
      /home/deployer/env/api-manager-postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.kong_postgres==1

  kong:
    image: kong:0.9.9
    env_file:
      /home/deployer/env/api-manager.env
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - default
      - application_default
    deploy:
      replicas: 1

  echo:
    image: sunbird/echo-server:0.0.1-bronze
    networks:
      - default
    deploy:
      replicas: 1

volumes:
  pgdata:
    driver: local

networks:
  application_default:
    external: true
