version: '3'

services:
  kong:
    image: sunbird/kong:0.9.9-bronze
    env_file:
      /home/deployer/env/api-manager.env
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - api-manager_default
      - "{{ sunbird_network }}"
    deploy:
      replicas: {{ kong_replicas }}
      update_config:
        parallelism: 1
        delay: 30s
    healthcheck:
      test: curl -f http://localhost:8001/status || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

  echo:
    image: "{{hub_org}}/{{echo_server_image_name}}:{{echo_server_image_tag}}"
    networks:
      - api-manager_default
    ports:
      - 9595:9595
    deploy:
      replicas: 1

volumes:
  pgdata:
    driver: local

networks:
  api-manager_default:
    external: true
  {{ sunbird_network }}:
    external: true
