node_exporter:
  reservation_memory: 16M
  limit_memory: 32M
cadvisor:
  reservation_memory: 64M
  limit_memory: 128M
elasticsearch_exporter:
  reservation_memory: 8M
  limit_memory: 16M
postgres_exporter:
  reservation_memory: 8M
  limit_memory: 16M
statsd_exporter:
  reservation_memory: 8M
  limit_memory: 16M
blackbox_exporter:
  reservation_memory: 16M
  limit_memory: 32M
jsonpath_exporter:
  reservation_memory: 16M
  limit_memory: 32M
azure_blob_exporter:
  reservation_memory: 16M
  limit_memory: 32M
monitor_logstash:
  replicas: 1
  heap_size: 512m
  reservation_memory: 1G
  limit_memory: 1G

# Override this at environment level
expected_minimum_logs_per_minute: 0
server_side_http_errors_threshold_percentage: 1

# Defaults to day (24 hours) with 1 hour slack interval
expected_data_backup_interval_in_minutes: "{{ 25 * 60 }}"

enable_postgres_availability_check: true
enable_mongodb_availability_check: true

enable_scraping_docker_metrics: false
docker_metrics_port: "2393"

kong_cluster_expected_number_of_nodes: "{{ kong_replicas | default(1) }}"

monitor_config_files_dest_dir: /opt/docker/stacks/monitor/config
prometheus_storage_retention_time: 168h0m0s

docker_service_replicas_exporter_version: v0.0.3
docker_service_replicas_exporter_name: docker-service-replicas-exporter

monitor_config_templates:
- file_name: prometheus.yml
  config_name: prometheus.yml
- file_name: alertmanagerconfig.yml
  config_name: alertmanagerconfig.yml
- file_name: blackboxconfig.yml
  config_name: blackboxconfig.yml
- file_name: postgresmasterqueries.yml
  config_name: postgresmasterqueries.yml
- file_name: postgresslavequeries.yml
  config_name: postgresslavequeries.yml
- file_name: statsd_mapping.yml
  config_name: statsd_mapping.yml
- file_name: kong_cluster_exporter_config.yml
  config_name: kong_cluster_exporter_config.yml
- file_name: data_backup_azure_blob_exporter_config.yml
  config_name: data_backup_azure_blob_exporter_config.yml
- file_name: alertrules.nodes
  config_name: prom_node_rules
- file_name: alertrules.task
  config_name: prom_container_rules
- file_name: alertrules.es
  config_name: prom_es_rules
- file_name: alertrules.logs
  config_name: prom_logs_rules
- file_name: alertrules.backups
  config_name: prom_backups_rules
- file_name: alertrules.kong
  config_name: prom_kong_rules
- file_name: alertrules.services
  config_name: prom_services_rules
- file_name: alertrules.docker
  config_name: prom_docker_rules
- file_name: alertrules.postgresql
  config_name: prom_postgresql_rules
- file_name: monitor_logstash.conf
  config_name: monitor_logstash.conf
- file_name: monitor_logstash_grok_patterns
  config_name: monitor_logstash_grok_patterns
- file_name: jmx_httpserver.yml
  config_name: jmx_httpserver.yml
- file_name: jmx_logging.properties
  config_name: jmx_logging.properties


prometheus:
  reservation_memory: 2G
  limit_memory: 4G
  alertmanager_route_prefix: alertmanager

prometheus_route_prefix: prometheus
prometheus_alertmanager_route_prefix: alertmanager

postgres_exporter_password: "{{ vault_postgres_exporter_password }}"
postgres_exporter_postgres_port: 5432
postgres_exporter_user: postgres_exporter
prometheus_scrape_interval: 15s

root_group: root
root_owner: root