node_exporter:
  reservation_memory: 16M
  limit_memory: 32M
cadvisor:
  reservation_memory: 64M
  limit_memory: 128M
elasticsearch_exporter:
  reservation_memory: 8M
  limit_memory: 16M
postgres_exporter:
  reservation_memory: 8M
  limit_memory: 16M
blackbox_exporter:
  reservation_memory: 16M
  limit_memory: 32M
