---
- name: Remove actor service
  shell: "docker service rm actor-service"

- name: Deploy actor service
  shell: "docker service create --replicas 1 -p 8088:8088 --name actor-service --hostname actor-service --network {{ sunbird_network }} --env-file /home/deployer/env/sunbird_actor-service.env sunbird/actor_service"
  args:
    chdir: /home/deployer/stack
