---
- name: Remove learner service
  shell: "docker service rm learner-service"
  ignore_errors: yes

- name: Deploy learner service
  shell: "docker service create --replicas {{ learner.replicas | default(1) }} -p 9000:9000  --name learner-service --hostname learner-service --reserve-memory {{ learner.reservation_memory |  default('768M') }} --limit-memory {{ learner.limit_memory |  default('1024M') }}  --network {{ sunbird_network }} --env-file /home/deployer/env/sunbird_learner-service.env {{hub_org}}/{{image_name}}:{{image_tag}}"
  args:
    chdir: /home/deployer/stack
