---
- name: Ensure env directory exists
  file:
    path: /home/deployer/env
    state: directory
    owner: root
    group: root

- name: Ensure stack directory exists
  file:
    path: /home/deployer/stack
    state: directory
    owner: root
    group: root

- name: Save actor configurations into an env file
  template: src=sunbird_actor.env dest=/home/deployer/env/sunbird_actor.env mode=0644

- name: Save content configurations into an env file
  template: src=sunbird_content.env dest=/home/deployer/env/sunbird_content.env mode=0644

- name: Save learner configurations into an env file
  template: src=sunbird_learner.env dest=/home/deployer/env/sunbird_learner.env mode=0644

- name: Save player configurations into an env file
  template: src=sunbird_player.env dest=/home/deployer/env/sunbird_player.env mode=0644

- name: Save configurations into an env file
  template: src=sunbird.env dest=/home/deployer/env/sunbird.env mode=0644

- name: Save stack file
  template: src=stack-sunbird.yml dest=/home/deployer/stack/sunbird.yml mode=0644

- name: Deploy stack
  shell: "docker stack deploy -c sunbird.yml application"
  args:
    chdir: /home/deployer/stack
