---
- name: Restore ES from Azure backup
  uri:
    url: "http://{{ es_restore_host }}:9200/_snapshot/azurebackup/{{snapshot_number}}"
    method: POST

- name: "Wait for restore to be completed"
  uri:
    url: "http://{{ es_restore_host }}:9200/_snapshot/azurebackup/_status"
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: result
  until: result.json.snapshots[0].state == 'SUCCESS'
  retries: 120
  delay: 10
