version: '3.1'

services:
  elasticsearch:
    image: elasticsearch:2.4.5-alpine
    environment:
      - LOGSPOUT=ignore
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9201:9200'
    networks:
      - logger_logger

  kibana:
    image: sunbird/kibana:0.0.1-bronze
    environment:
      - LOGSPOUT=ignore
    depends_on:
      - logger_elasticsearch
    ports:
      - '5601:5601'
    networks:
      - logger_logger

  logstash:
    image: sunbird/logstash:0.0.1-bronze
    command: logstash -f /conf/logstash.conf
    environment:
      - LOGSPOUT=ignore
    depends_on:
      - logger_elasticsearch
    networks:
      - logger_logger

  logspout:
    image: gliderlabs/logspout
    command: syslog+tcp://logger_logstash:51415
    deploy:
      mode: global
    environment:
      - SYSLOG_FORMAT=rfc3164
    depends_on:
      - logger_logstash
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    networks:
      - logger_logger
      - api-manager_default
      - jenkins_default
      - monitor
      - application_default
  oauth:
    image: mryu/oauth2-proxy
    command: |
      -cookie-secure=false
      -upstream=http://logger_kibana:5601/
      -redirect-url=https://dev.open-sunbird.org/oauth2/callback
      -http-address=0.0.0.0:4111
      -email-domain=sahajsoft.com
      -email-domain=ilimi.in
      -email-domain=ekstep.org
    environment:
      - OAUTH2_PROXY_CLIENT_ID={{google_client_id}}
      - OAUTH2_PROXY_CLIENT_SECRET={{google_client_secret}}
      - OAUTH2_PROXY_COOKIE_SECRET={{cookie_secret}}
    ports:
      - "4111:4111"
    networks:
      - logger_logger

networks:
  api-manager_default:
    external: true
  jenkins_default:
    external: true
  monitor:
    external: true
  application_default:
    external: true
  logger_logger:
    external: true
