global:
  resolve_timeout: 5m
  smtp_from: "{{ monitor_alerts_mail_from_email }}"
  smtp_smarthost: "{{ monitor_alerts_mail_server_host }}:{{ monitor_alerts_mail_server_port}}"
  smtp_auth_username: "{{ monitor_alerts_mail_server_username }}"
  smtp_auth_password: "{{ monitor_alerts_mail_server_password }}"
  smtp_require_tls: true

route:
  repeat_interval: 15m
  group_interval: 5m
  group_wait: 1m
  routes:
  - match:
      owner: devops_team
    receiver: devops_team
    continue: true
  - match:
      owner: app_team
    receiver: app_team
    continue: true
  - match:
      owner: site_team
    receiver: site_team
    continue: true
  - match:
      alertstate: firing
    receiver: all

receivers:
  - name: 'all'
    slack_configs:
      - send_resolved: true
        api_url: "{{slack_url}}"
        username: 'Monitor - Alerter'
        channel: "{{slack_channel}}"
        text: "Instances: {% raw %}{{range .Alerts}}\n{{.Labels.instance}} : {{.Annotations.description}}{{end}}{% endraw %}"
        icon_emoji: ':dart:'
    email_configs:
      - send_resolved: true
        to: '{{ monitor_alerts_mail_to_email }}'
        html: '{% raw %}{{ template "email.default.html" . }}{% endraw %}<br/>Instances: {% raw %}{{range .Alerts}}<br/>{{.Labels.instance}} : {{.Annotations.description}}{{end}}{% endraw %}'
        headers:
          subject: '[{{ env }}] {% raw %}{{ template "email.default.subject" . }}{% endraw %}'

  - name: 'devops_team'
    email_configs:
      - send_resolved: true
        to: '{{ devops_alerts_mailing_list }}'
        html: '{% raw %}{{ template "email.default.html" . }}{% endraw %}<br/>Instances: {% raw %}{{range .Alerts}}<br/>{{.Labels.instance}} : {{.Annotations.description}}{{end}}{% endraw %}'
        headers:
          subject: '[{{ env }}-devops] {% raw %}{{ template "email.default.subject" . }}{% endraw %}'

  - name: 'app_team'
    email_configs:
      - send_resolved: true
        to: '{{ app_alerts_mailing_list }}'
        html: '{% raw %}{{ template "email.default.html" . }}{% endraw %}<br/>Instances: {% raw %}{{range .Alerts}}<br/>{{.Labels.instance}} : {{.Annotations.description}}{{end}}{% endraw %}'
        headers:
          subject: '[{{ env }}-app] {% raw %}{{ template "email.default.subject" . }}{% endraw %}'

  - name: 'site_team'
    email_configs:
      - send_resolved: true
        to: '{{ site_alerts_mailing_list }}'
        html: '{% raw %}{{ template "email.default.html" . }}{% endraw %}<br/>Instances: {% raw %}{{range .Alerts}}<br/>{{.Labels.instance}} : {{.Annotations.description}}{{end}}{% endraw %}'
        headers:
          subject: '[{{ env }}-site] {% raw %}{{ template "email.default.subject" . }}{% endraw %}'
