modules:
  http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2"]
        valid_status_codes: []  # Defaults to 2xx
        method: GET
  composite_search:
      prober: http
      timeout: 5s
      http:
        method: POST
        headers:
          Content-Type: application/json
          Authorization: Bearer {{ kong__test_jwt }}
        body: '{
          "request": {
            "filters":{
              "contentType": "Course",
              "objectType": ["Content"],
              "status": ["Live"]
            },
            "limit": 1,
            "fields": ["name", "contentType"]
            }
          }'
  page_assemble:
      prober: http
      timeout: 5s
      http:
        method: POST
        headers:
          Content-Type: application/json
          Authorization: Bearer {{ kong__test_jwt }}
        body: '{"request": {"source": "web", "name": "Resource", "filters": {}}}'
