---
hostPort: {{ cassandra_listen_address }}:7199
username:
password:

whitelistObjectNames: ["org.apache.cassandra.metrics.IndexColumnFamily.FifteenMinuteRate:*"]
blacklistObjectNames: ["org.apache.cassandra.metrics:type=ColumnFamily,*"]
