global:
  scrape_interval:     5s
  evaluation_interval: 15s
  external_labels:
    monitor: 'Prometheus-Monitor'
  
rule_files:
  - '/etc/prometheus-rules/alertrules.nodes'
  - '/etc/prometheus-rules/alertrules.task'

scrape_configs:
  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'alertmanager'
    dns_sd_configs:
    - names:
      - 'tasks.alertmanager'
      type: 'A'
      port: 9093

  - job_name: 'root'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
    - targets:
      - https://{{api__host}}
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: monitor_blackbox-exporter:9115  # Blackbox exporter.

  - job_name: 'composite_search'
    metrics_path: /probe
    params:
      module: [composite_search]  # Look for a HTTP 200 response.
    static_configs:
    - targets:
      - https://{{api__host}}/api/composite/v1/search
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: monitor_blackbox-exporter:9115  # Blackbox exporter.

  - job_name: 'page_assemble'
    metrics_path: /probe
    params:
      module: [page_assemble]  # Look for a HTTP 200 response.
    static_configs:
    - targets:
      - https://{{api__host}}/api/data/v1/page/assemble
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: monitor_blackbox-exporter:9115  # Blackbox exporter.

  - job_name: 'auth'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
    - targets:
      - https://{{api__host}}/auth/realms/sunbird/protocol/openid-connect/auth?client_id=portal&state=foo&redirect_uri=https%3A%2F%2Fdev.open-sunbird.org%2Fprivate%2Findex%3Fauth_callback%3D1&scope=openid&response_type=code
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: monitor_blackbox-exporter:9115  # Blackbox exporter.
