mappings:
- match: kong.*.request.count
  name: "kong_request_count"
  labels:
    api: "$1"
- match: kong.*.request.status.*
  name: "kong_request_status_count"
  labels:
    api: "$1"
    status_code: "$2"
- match: kong.*.latency
  name: "kong_latency_time"
  labels:
    api: "$1"
- match: kong.*.upstream_latency
  name: "kong_upstream_latency_time"
  labels:
    api: "$1"
- match: kong.*.request.size
  name: "kong_request_size"
  labels:
    api: "$1"
- match: kong.*.response.size
  name: "kong_response_size"
  labels:
    api: "$1"
