mappings:
- match: kong.*.request.count
  labels:
    name: "kong_request"
    api: "$1"
- match: kong.*.request.status.*
  labels:
    name: "kong_request_status"
    api: "$1"
    status: "$2"
- match: kong.*.latency
  labels:
    name: "kong_latency"
    api: "$1"
- match: kong.*.upstream_latency
  labels:
    name: "kong_upstream_latency"
    api: "$1"
- match: kong.*.request.size
  labels:
    name: "kong_request_size"
    api: "$1"
- match: kong.*.response.size
  labels:
    name: "kong_response_size"
    api: "$1"
