mappings:
- match: kong.*.request.count
  labels:
    name: "kong_request_count"
    api: "$1"
- match: kong.*.request.status.*
  labels:
    name: "kong_request_status_count"
    api: "$1"
    status_code: "$2"
- match: kong.*.latency
  labels:
    name: "kong_latency_time"
    api: "$1"
- match: kong.*.upstream_latency
  labels:
    name: "kong_upstream_latency_time"
    api: "$1"
- match: kong.*.request.size
  labels:
    name: "kong_request_size"
    api: "$1"
- match: kong.*.response.size
  labels:
    name: "kong_response_size"
    api: "$1"
- match: nginx.log.statuscode.*
  labels:
    name: "nginx_request_status_count"
    status_code: $1
- match: nginx.log.responsetime
  labels:
    name: "nginx_response_time"
