---

- name: Ensure stack directory exists
  file:
    path: /home/deployer/stack
    state: directory
    owner: root
    group: root
  
- name: Ensure config directory exists
  file:
    path: /home/deployer/config
    state: directory
    owner: root
    group: root

- name: Save stack file
  template: src=stack-monitor.yml dest=/home/deployer/stack/monitor.yml mode=0644

- name: Save prometheus config file
  template: src=prometheus.yml dest=/home/deployer/config/prometheus.yml mode=0644

- name: Save alertmanager config file
  template: src=alertmanagerconfig.yml dest=/home/deployer/config/alertmanagerconfig.yml mode=0644

- name: Save blackboxconfig config file
  template: src=blackboxconfig.yml dest=/home/deployer/config/blackboxconfig.yml mode=0644

- name: Save prometheus node rule file
  copy: src=alertrules.nodes dest=/home/deployer/config/alertrules.nodes mode=0644

- name: Save prometheus container rule file
  copy: src=alertrules.nodes dest=/home/deployer/config/alertrules.task mode=0644

- name: Remove monitor stack
  shell: "docker stack rm monitor"
  ignore_errors: yes

- name: Remove old prometheus.yml docker config
  shell: "docker config rm prometheus.yml"
  ignore_errors: yes

- name: Remove old prom_node_rules docker config
  shell: "docker config rm prom_node_rules"
  ignore_errors: yes

- name: Remove old prom_container_rules docker config
  shell: "docker config rm prom_container_rules"
  ignore_errors: yes

- name: Remove old alermanager docker config
  shell: "docker config rm alertmanagerconfig.yml"
  ignore_errors: yes

- name: Remove old alermanager docker config
  shell: "docker config rm blackboxconfig.yml"
  ignore_errors: yes

- name: Save prometheus.yml docker config
  shell: "docker config create prometheus.yml /home/deployer/config/prometheus.yml"
  ignore_errors: yes

- name: Save prom_node_rules docker config
  shell: "docker config create prom_node_rules /home/deployer/config/alertrules.nodes"
  ignore_errors: yes

- name: Save prom_container_rules docker config
  shell: "docker config create prom_container_rules /home/deployer/config/alertrules.task"
  ignore_errors: yes

- name: Save alermanager docker config
  shell: "docker config create alertmanagerconfig.yml /home/deployer/config/alertmanagerconfig.yml"
  ignore_errors: yes

- name: Save alermanager docker config
  shell: "docker config create blackboxconfig.yml /home/deployer/config/blackboxconfig.yml"
  ignore_errors: yes

- name: Deploy stack
  shell: "docker stack deploy -c monitor.yml monitor"
  args:
    chdir: /home/deployer/stack
