---

- name: Ensure stack directory exists
  file:
    path: /opt/docker/stacks/monitor/stack
    state: directory
    owner: '{{ root_owner }}'
    group: '{{ root_group }}'

- name: Ensure config directory exists
  file:
    path: /opt/docker/stacks/monitor/config
    state: directory
    owner: '{{ root_owner }}'
    group: '{{ root_group }}'

- name: Save stack file
  template: src=stack-monitor.yml dest=/opt/docker/stacks/monitor/stack/monitor.yml mode=0644

- name: Save stack file
  shell: "cat /opt/docker/stacks/monitor/stack/monitor.yml"

- name: Save prometheus config file
  template: src=prometheus.yml dest=/opt/docker/stacks/monitor/config/prometheus.yml mode=0644

- name: Save alertmanager config file
  template: src=alertmanagerconfig.yml dest=/opt/docker/stacks/monitor/config/alertmanagerconfig.yml mode=0644

- name: Save blackboxconfig config file
  template: src=blackboxconfig.yml dest=/opt/docker/stacks/monitor/config/blackboxconfig.yml mode=0644

- name: Save postgresmasterqueries config file
  template: src=postgresmasterqueries.yml dest=/opt/docker/stacks/monitor/config/postgresmasterqueries.yml mode=0644

- name: Save postgresslavequeries config file
  template: src=postgresslavequeries.yml dest=/opt/docker/stacks/monitor/config/postgresslavequeries.yml mode=0644

- name: Save prometheus node rule file
  copy: src=alertrules.nodes dest=/opt/docker/stacks/monitor/config/alertrules.nodes mode=0644

- name: Save prometheus container rule file
  copy: src=alertrules.task dest=/opt/docker/stacks/monitor/config/alertrules.task mode=0644

- name: Save prometheus postgresql rule file
  copy: src=alertrules.postgresql dest=/opt/docker/stacks/monitor/config/alertrules.postgresql mode=0644

- name: Remove monitor stack
  shell: "docker stack rm monitor"
  ignore_errors: yes

- name: Remove old prometheus.yml docker config
  shell: "docker config rm prometheus.yml"
  ignore_errors: yes

- name: Remove old prom_node_rules docker config
  shell: "docker config rm prom_node_rules"
  ignore_errors: yes

- name: Remove old prom_container_rules docker config
  shell: "docker config rm prom_container_rules"
  ignore_errors: yes

- name: Remove old prom_postgresql_rules docker config
  shell: "docker config rm prom_postgresql_rules"
  ignore_errors: yes

- name: Remove old alermanager docker config
  shell: "docker config rm alertmanagerconfig.yml"
  ignore_errors: yes

- name: Remove old blackboxconfig docker config
  shell: "docker config rm blackboxconfig.yml"
  ignore_errors: yes

- name: Remove old postgresmasterqueries docker config
  shell: "docker config rm postgresmasterqueries.yml"
  ignore_errors: yes

- name: Remove old postgresslavequeries docker config
  shell: "docker config rm postgresslavequeries.yml"
  ignore_errors: yes

- name: Save prometheus.yml docker config
  shell: "docker config create prometheus.yml /opt/docker/stacks/monitor/config/prometheus.yml"
  ignore_errors: yes

- name: Save prom_node_rules docker config
  shell: "docker config create prom_node_rules /opt/docker/stacks/monitor/config/alertrules.nodes"
  ignore_errors: yes

- name: Save prom_container_rules docker config
  shell: "docker config create prom_container_rules /opt/docker/stacks/monitor/config/alertrules.task"
  ignore_errors: yes

- name: Save prom_postgresql_rules docker config
  shell: "docker config create prom_postgresql_rules /opt/docker/stacks/monitor/config/alertrules.postgresql"
  ignore_errors: yes

- name: Save alermanager docker config
  shell: "docker config create alertmanagerconfig.yml /opt/docker/stacks/monitor/config/alertmanagerconfig.yml"
  ignore_errors: yes

- name: Save blackboxconfig docker config
  shell: "docker config create blackboxconfig.yml /opt/docker/stacks/monitor/config/blackboxconfig.yml"
  ignore_errors: yes

- name: Save postgresmasterqueries docker config
  shell: "docker config create postgresmasterqueries.yml /opt/docker/stacks/monitor/config/postgresmasterqueries.yml"
  ignore_errors: yes

- name: Save postgresslavequeries docker config
  shell: "docker config create postgresslavequeries.yml /opt/docker/stacks/monitor/config/postgresslavequeries.yml"
  ignore_errors: yes

- name: Deploy stack
  shell: "docker stack deploy -c monitor.yml monitor"
  args:
    chdir: /opt/docker/stacks/monitor/stack
