---
- name: Ensure stack directory exists
  file:
    path: /opt/docker/stacks/monitor/stack
    state: directory
    owner: '{{ root_owner }}'
    group: '{{ root_group }}'

- name: Ensure config directory exists
  file:
    path: "{{ monitor_config_files_dest_dir }}"
    state: directory
    owner: '{{ root_owner }}'
    group: '{{ root_group }}'

- name: Save stack file
  template: src=stack-monitor.yml dest=/opt/docker/stacks/monitor/stack/monitor.yml mode=0644

- name: Save stack file
  shell: "cat /opt/docker/stacks/monitor/stack/monitor.yml"

- name: Save prometheus config {{ item.file_name }}
  template: src={{ item.file_name }} dest="{{ monitor_config_files_dest_dir }}/{{ item.file_name }}" mode=0644
  with_items: "{{ monitor_config_templates }}"

- name: Remove monitor stack
  shell: "docker stack rm monitor"
  ignore_errors: yes

- name: Remove old docker config {{ item.config_name }}
  shell: "docker config rm {{ item.config_name }}"
  with_items: "{{ monitor_config_templates }}"
  ignore_errors: yes

- name: Save docker config {{ item.config_name }}
  shell: "docker config create {{ item.config_name }} {{ monitor_config_files_dest_dir }}/{{ item.file_name }}"
  with_items: "{{ monitor_config_templates }}"
  ignore_errors: yes

- name: Deploy stack
  shell: "docker stack deploy -c monitor.yml monitor"
  args:
    chdir: /opt/docker/stacks/monitor/stack
