---

- name: Ensure stack directory exists
  file:
    path: /home/deployer/stack
    state: directory
    owner: root
    group: root

- name: Save stack file
  template: src=stack-monitor.yml dest=/home/deployer/stack/monitor.yml mode=0644

- name: Deploy stack
  shell: "docker stack deploy -c monitor.yml monitor-{{env}}"
  args:
    chdir: /home/deployer/stack
