small_rate_limit_per_hour: 5000
medium_rate_limit_per_hour: 30000
large_rate_limit_per_hour: 30000

# Consumers to be on-boarded
kong_consumers:
  - username: api-management-test-user
    groups: "{{ kong_all_consumer_groups }}"
    state: present
  - username: qci-user
    groups:  "{{ integration_partner_groups }}"
    state: present
    credential_algorithm: "RS256"
    credential_rsa_public_key: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA/Fdy/zzU4LQMM7t9zDaA\n6rCPMkk3pVYgDBYXND4JjVVYa9Xb/wfiIBiZtVbRZSRCkEtlD6reqDeMkRzuKoNm\nCYOUVLnjjposlwmzUASGhLQOLJknPJGWaCWRGVIXiQc956cNwx7NDIcPblsa0O8K\nkEeXEOXew3gkXaNkJOEgHZCzVu4TKh6F+GRp159jZnoQpJF4bLkwzTdsmpVu/dOG\nDt4YNwkjtpk60WN/wDbN1wlBWE3HqZ/+xNFPw1pteJUJIW4EW9+P5Qb7c8ZghCZw\nm1W+/TCU06BmN2yzGpnTFGd5ru8wbY2eP1rOpdauL6c86qcvmsXPmUutO8P0OEkd\nswIDAQAB\n-----END PUBLIC KEY-----"
    credential_iss: "qci"
  - username: mobile_admin
    groups: "{{ mobile_admin_groups }}"
    print_credentials: true
    state: present
  - username: mobile_app
    groups: "{{ mobile_app_groups }}"
    state: present
  - username: mobile_device
    groups: "{{ mobile_device_groups }}"
    state: present
  - username: add-any-consumer-to-be-deleted
    state: absent
  - username: apekx-integrator-user
    groups: "{{ integration_partner_groups }}"
    state: present
    credential_algorithm: "RS256"
    credential_rsa_public_key: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlvpTfnp9YCLsFNvzNo4D\nNUrxn8y+8BNKqPs277Z5XrOIRiypMJ+D/f8tGOdUiHPYwmNLPhHC0PhERlfCWmzd\nZf+WeNrgQPrfPSLGaUMQOGPTj5b8cw+8cZU3x5h6wLv/g3acc/BRn5vodQ2jQejR\nwDznwxaAIOqUeq0AwJU0/97YrXm9FWW07EhcFdbJY2hVkRkU+da9WYGIWm3Dki2c\nT0FhesSPPebG8bsRvbppviB9vHrNXS3rw0JVwMIbMogk8MoBqRIZraO2CvzLxlyN\nPTbZzbTxeEZk+dS6gzgYDglD9neTNo+8DJVv0H6yEpPWCqz89rFUwBpLmD9lRP0q\ndwIDAQAB\n-----END PUBLIC KEY-----"
    credential_iss: "apekx"
  - username: ntp-implementation-user
    groups: "{{ implementaion_user_groups }}"
    state: present
