---

- include_vars: secrets/{{env}}.yml

- name: Ensure stack directory exists
  file:
    path: /home/deployer/stack
    state: directory
    owner: root
    group: root

- name: Save stack file
  template: src=stack-logger.yml dest=/home/deployer/stack/logger.yml mode=0644

- name: Deploy stack
  shell: "docker stack deploy -c logger.yml logger"
  args:
    chdir: /home/deployer/stack
