---
kong_admin_api_url: "http://localhost:8001"

# List all consumer groups in group_vars
kong_all_consumer_groups: []

# List the consumers need to be present as state: present
# List the consumers need to be absent as state: absent
# This role will not update / delete consumers not listed here
kong_consumers:
  - username: api-management-test-user
    groups: "{{ kong_all_consumer_groups }}"
    state: present
  - username: add-any-consumer-to-be-deleted
    state: absent
