---
user: root
group: root
slack_channel: 
slack_user: Monit
slack_web_hook: 

monit_cassandra:
  app_name: cassandra
  custom_start: /usr/sbin/service cassandra start
  custom_stop: /usr/sbin/service cassandra stop
  timeout: "30"
  retry: 3
