---
- name: Copying dialpage redirect config
  template: src=nginx-opensaber.conf dest=/home/deployer/nginx-opensaber.conf
  register: opensaber_nginx
  
- name: Updating nginx-opensaber.conf
  block:
    - shell: docker config rm opensaber_nginx.conf
      ignore_errors: yes
    - shell: docker config create opensaber_nginx.conf /home/deployer/nginx-opensaber.conf
    - shell: docker service update --config-add src=opensaber_nginx.conf,target=/etc/nginx/conf.d/nginx-opensaber.conf proxy_proxy
  become: yes
  when: opensaber_nginx.changed
