version: '3.1'

services:
  player:
    image: "{{hub_org}}/{{image_name}}:{{image_tag}}"
    deploy:
      replicas: {{ player.replicas | default(1) }}
      resources:
        limits:
          memory: "{{player.limit_memory}}"
        reservations:
          memory: "{{player.reservation_memory}}"
    env_file:
      /home/deployer/env/sunbird_player.env
    ports:
     - "3000:3000"
    networks:
      - "{{ sunbird_network }}"

networks:
  {{ sunbird_network }}:
    external: true
