version: '3.1'

services:
  content_service:
    image: "{{hub_org}}/{{image_name}}:{{image_tag}}"
    env_file:
      /home/deployer/env/sunbird_content_service.env
    deploy:
      replicas: 1
    ports:
     - "5000:5000"
    networks:
      - "{{ sunbird_network }}"

networks:
  {{ sunbird_network }}:
    external: true
