version: '3.1'

services:
  content_service:
    image: "{{hub_org}}/{{image_name}}:{{image_tag}}"
    deploy:
      replicas: {{ content.replicas | default(1) }}
      resources:
        reservations: 
          memory: "{{ content.reservation_memory  | default('64M') }}"
        limits:
          memory: "{{ content.limit_memory | default('256M') }}"
    env_file:
      /home/deployer/env/sunbird_content_service.env
    ports:
     - "5000:5000"
    networks:
      - "{{ sunbird_network }}"

networks:
  {{ sunbird_network }}:
    external: true
