version: '3.1'

services:
  player:
    image : "manojrpms/sunbird_player_image:latest"
    deploy:
      replicas: 1
    env_file:
      /home/deployer/env/sunbird_player.env
    ports:
     - "3000:3000"
    networks:
      - default

  content:
    image : "manojrpms/sunbird_content_service_image:latest"
    env_file:
      /home/deployer/env/sunbird_content.env
    deploy:
      replicas: 1
    ports:
     - "5000:5000"
    networks:
      - default

  learner:
    image : "manojrpms/sunbird_learner_service_image:latest"
    env_file:
      /home/deployer/env/sunbird_learner.env
    deploy:
      replicas: 1
    ports:
     - "9000:9000"
    networks:
      - default
volumes:
  application_cassandra:
    driver: local
  elasticsearch:
    driver: local

networks:
  default:
    driver: overlay

