groups:
- name: alertrules.kafka_lag
  rules:
  - alert: secor sunbirddev.telemetry.ingestion.backup consumer group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="sunbirddev.telemetry.ingestion.backup"} > 10
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'secor telemetry.ingestion.backup consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for telemetry.ingestion.backup
