groups:
- name: alertrules.services
  rules:
  - alert: service_down
    expr: probe_success == 0
    for: 1m
    annotations:
      description: '{% raw %}{{ $labels.job }}{% endraw %}: The service is down.'
      summary: Service down
  - alert: health_check
    expr: changes(probe_success[5m]) > 2
    for: 2m
    annotations:
      description: 'The service status has changed {% raw %}{{$value}}{% endraw %} times in last 2 minutes. Threshold is : 2'
      summary: Health check is failing 
