groups:
- name: alertrules.kafka_lag
  rules:
  - alert: consumer group lag is more for sunbirddev.telemetry.ingestion.backup
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="sunbirddev.telemetry.ingestion.backup"} > 10
    for: 5m
    labels:
      severity: critical
    annotations:
      description: consumer group lag is {% raw %}{{$value}}{% endraw %} for telemetry.ingestion.backup secor job
      summary: consumer group lag is more for telemetry.ingestion.backup
