groups:
- name: alertrules.redis
  rules:
  - alert: redis_not_running_FATAL
    expr: redis_up{job="redis_exporter"} < 1
    for: 1m
    labels:
      severity: FATAL
    annotations:
      description: 'Redis is not Running'
      summary: Redis Process is not running
