groups:
- name: alertrules.kafka_lag
  rules:
  - alert: secor {{ kafka_topic_prefix }}.ingestion.backup consumer group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.telemetry.ingestion.backup"} > {{ telemetry_ingestion_backup_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.telemetry.ingestion.backup consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.telemetry.ingestion.backup
