groups:
- name: alertrules.kafka_lag
  rules:
  - alert: secor {{ kafka_topic_prefix }}.events.deviceprofile.backup group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.events.deviceprofile.backup"} > {{ events_deviceprofile_backup_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.events.deviceprofile.backup consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.events.deviceprofile.backup
  - alert: secor {{ kafka_topic_prefix }}.telemetry.channel.backup group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.telemetry.channel.backup"} > {{ telemetry_channel_backup_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.telemetry.channel.backup consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.telemetry.channel.backup
  - alert: secor {{ kafka_topic_prefix }}.telemetry.derived.backup group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.telemetry.derived.backup"} > {{ telemetry_derived_backup_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.telemetry.derived.backup consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.telemetry.derived.backup
  - alert: secor {{ kafka_topic_prefix }}.telemetry.failed.backup group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.telemetry.failed.backup"} > {{ telemetry_failed_backup_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.telemetry.failed.backup consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.telemetry.failed.backup
  - alert: secor {{ kafka_topic_prefix }}.telemetry.ingestion.backup consumer group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.telemetry.ingestion.backup"} > {{ telemetry_ingestion_backup_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.telemetry.ingestion.backup consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.telemetry.ingestion.backup
  - alert: secor {{ kafka_topic_prefix }}.graph.events.backup consumer group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.graph.events.backup"} > {{ graph_events_backup_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.graph.events.backup consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.graph.events.backup  
  - alert: secor {{ kafka_topic_prefix }}.telemetry.raw.backup consumer group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.telemetry.raw.backup"} > {{ telemetry_raw_backup_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.telemetry.raw.backup consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.telemetry.raw.backup
  - alert: secor {{ kafka_topic_prefix }}.telemetry.unique.backup consumer group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.telemetry.unique.backup"} > {{ telemetry_unique_backup_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.telemetry.unique.backup consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.telemetry.unique.backup
  - alert: secor {{ kafka_topic_prefix }}.learning.failed.events.backup consumer group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.learning.failed.events.backup"} > {{ learning_failed_events_backup_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.learning.failed.events.backup consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.learning.failed.events.backup
  - alert: secor {{ kafka_topic_prefix }}.telemetry.denorm.backup consumer group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.telemetry.denorm.backup"} > {{ telemetry_denorm_backup_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.telemetry.denorm.backup consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.telemetry.denorm.backup         
  - alert: secor {{ kafka_topic_prefix }}.pipeline_metrics consumer group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.pipeline_metrics"} > {{ pipeline_metrics_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.pipeline_metrics consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.pipeline_metrics
  - alert: secor {{ kafka_topic_prefix }}.telemetry.extractor.failed consumer group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.telemetry.extractor.failed"} > {{ telemetry_extractor_failed_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.telemetry.extractor.failed consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.telemetry.extractor.failed         
  - alert: secor {{ kafka_topic_prefix }}.telemetry.assess consumer group lag
    expr: kafka_consumergroupzookeeper_lag_zookeeper{consumergroup="{{ kafka_topic_prefix }}.telemetry.assess"} > {{ telemetry_assess_threshold }}
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ kafka_topic_prefix }}.telemetry.assess consumer group lag is {% raw %}{{$value}}{% endraw %} for partition: {% raw %}{{ $labels.partition }}{% endraw %}'
      summary: secor consumer group lag is more for {{ kafka_topic_prefix }}.telemetry.assess
