snapshot_create_request_body: {
    type: s3,
    settings: {
      bucket: "{{ es_s3_backup_folder_name }}",
      base_path: "{{ snapshot_base_path }}_{{ base_path_date }}"
    }
}

# Override these values
es_snapshot_host: "localhost"
snapshot_base_path: "default"

es_s3_backup_folder_name: "elasticsearch-snapshots"