- name: Add Azure apt repository
  apt_repository: repo='deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main' state=present

- name: Import Azure signing key
  apt_key: keyserver=packages.microsoft.com id=417A0893

- name: ensure apt-transport-https is installed
  apt: name=apt-transport-https

- name: ensure azure-cli is installed
  apt: name=azure-cli update_cache=yes