- name: Debian - Add Elasticsearch repository key
  apt_key: url="https://artifacts.elastic.co/GPG-KEY-elasticsearch" state=present

- name: Add curator repo
  apt_repository: repo='deb [arch=amd64] http://packages.elastic.co/curator/5/debian9 stable main' state=present update_cache=yes

- name: Install elasticsearch curator
  apt:
    name: elasticsearch-curator=5.2.0

- name: Ensure curator config dir exists
  file: dest="{{es_curator_config_dir}}" state=directory

- name: Create curator.yml
  template: src=curator.yml dest="{{es_curator_config_file}}"

- name: Create snapshot-purge-action.yml
  template: src=snapshot-purge-action.yml dest="{{es_curator_config_dir}}/snapshot-purge-action.yml"

- name: Delete snapshots older than {{ es_snapshot_retention_days }} days
  shell: "curator --config {{ es_curator_config_file }} {{es_curator_config_dir}}/snapshot-purge-action.yml"
  async: 108000
  poll: 10
