- name: Clean artifact path
  file:
    state: absent
    path: "{{ cql_output_root_dir }}"

- name: Clean artifact path
  file:
    state: absent
    path: "{{ csv_output_root_dir }}"

- name: Ensure CQL directory exists
  file:
    path: "{{ cql_output_root_dir }}"
    state: directory

- name: Ensure CSV directory exists
  file:
    path: "{{ csv_output_root_dir }}"
    state: directory

- name: Save CQL
  template: src="{{ item }}.cql" dest="/tmp/cql/{{ item }}.cql"
  with_items: "{{ cqls }}"

- shell: 'cqlsh --debug -f /tmp/cql/{{ item }}.cql'
  with_items: "{{ cqls }}"

# - name: get the csv reports
#   become: yes 
#   synchronize: mode=pull src="{{ csv_output_root_dir }}/{{ item }}.csv" dest=./
#   with_items: "{{ cqls }}"

- name: 'Test | synchronize'
  become: yes
  synchronize: src="{{ csv_output_root_dir }}/{{ item }}.csv"  dest=./ recursive=yes delete=yes rsync_path="sudo rsync"
  with_items: "{{ cqls }}"

# - fetch:
#     src: "{{ csv_output_root_dir }}/{{ item }}.csv"
#     dest: ./
#     fail_on_missing: yes
#     flat: yes
 #  with_items: "{{ cqls }}"