- name: Clean artifact path
  file:
    state: absent
    path: "/tmp/cql"

- name: Ensure CQL directory exists
  file:
    path: /tmp/cql/csv
    state: directory

- name: Save CQL
  copy: src=sunbird_orgs.cql dest=/tmp/cql/sunbird_orgs.cql

- shell: 'cqlsh --debug -f /tmp/cql/sunbird_orgs.cql'

- shell: 'cat /tmp/cql/csv/sunbird_orgs.csv'

- fetch:
    src: /tmp/cql/csv/sunbird_orgs.csv
    dest: /tmp/fetched/
    fail_on_missing: yes
    flat: yes