- name: Cassandra | Update the cassandra host configuration
  become: yes
  template: src=hosts.j2 dest=/etc/hosts
  tags: 
       - provision


- name: debian | Adding Cassandra Debian Repo Key
  apt_key:
    url: "{{ cassandra_repo_key }}"
    state: "present"
  tags: 
       - provision

- name: debian | Adding Cassandra Debian Repo
  apt_repository:
    repo: "{{ cassandra_repo }}"
    state: "present"
  tags: 
       - provision

- name: debian | Installing Cassandra
  apt:
    name: "cassandra"
    state: "present"
  tags: 
       - provision


- name: config | Configuring Cassandra
  template:
    src: "cassandra.yaml.j2"
    dest: "{{ cassandra.root_dir }}/cassandra.yaml"
    owner: "root"
    group: "root"
    mode: 0644
  notify: "restart cassandra"
  tags: 
       - provision


- name: Copy the templates
  become: yes
  template: src={{item}} dest=/tmp/{{item}}
  with_items:
             - cassandra.cql
             - pageMgmt.csv
             - pageSection.csv
  tags: 
       - provision


- name: Run the cassandra.cql command
  become: yes
  command: "cqlsh -f /tmp/cassandra.cql"
  ignore_errors: yes
  tags: 
       - load_cql

- name: Run the pageMgmt.csv command
  become: yes
  command: cqlsh -e "COPY sunbird.page_management(id, appmap,createdby ,createddate ,name ,organisationid ,portalmap ,updatedby ,updateddate ) FROM '/tmp/pageMgmt.csv'" 
  ignore_errors: yes
  tags: 
       - load_management

- name: Run the pageSection.csv file
  become: yes
  command: cqlsh -e "COPY sunbird.page_section(id, alt,createdby ,createddate ,description ,display ,imgurl ,name,searchquery , sectiondatatype ,status , updatedby ,updateddate) FROM '/tmp/cql/pageSection.csv'"
  ignore_errors: yes
  tags: 
       - load_section

- name: Create the directory
  become: yes
  file: path=/data/cassandra/ state=directory recurse=yes
  tags: 
       - backup


- name: Create Symlink
  become: yes
  command: sudo ln -s /var/lib/cassandra/data /data/cassandra/data 
  tags: 
       - backup

- name: copy the backup script 
  become: yes
  template: src=cassandra_backup.j2  dest=/home/deployer/cassandra_backup.sh mode=0755 
  tags: 
       - backup

- name: run the backup script
  become: yes
  shell: sh /home/deployer/cassandra_backup.sh
  tags: 
       - backup
 
- name: Add Azure apt repository
  apt_repository: repo='deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main' state=present

- name: Import Azure signing key
  apt_key: keyserver=packages.microsoft.com id=417A0893

- name: ensure apt-transport-https is installed
  apt: name=apt-transport-https

- name: ensure azure-cli is installed
  apt: name=azure-cli update_cache=yes

- name: Ensure azure blob storage container exists
  command: az storage container create  --name {{ cassandra.backup_azure_container_name }}
  ignore_errors: true
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ cassandra.backup_azure_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ cassandra.backup_azure_storage_access_key }}"

- name: Upload to azure blob storage
  command: az storage blob upload --name {{ cassandra.backup_gzip_file_name }} --file {{ cassandra.backup_gzip_file_path }} --container-name {{ cassandra.backup_azure_container_name }}
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ cassandra.backup_azure_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ cassandra.backup_azure_storage_access_key }}"
  async: 3600
  poll: 10

- name: clean up backup dir after upload
  file: path="{{ cassandra.backup_dir }}" state=absent