# ---
# - name: debian | update package list
#   apt:
#     update_cache: yes
#     cache_valid_time: 3600

# - name: debian | Installing Pre-Reqs
#   apt:
#     name: "{{ item }}"
#     force: yes
#     state: "present"
#   with_items:
#     - 'apt-transport-https'
#     - 'ca-certificates'
#     - 'python-pip'
#     - 'libssl-dev'

# - name: debian |  Upgrade pip
#   pip:
#     name: pip
#     extra_args: --upgrade

# - name: debian | Installing Python Modules
#   pip:
#     name: "{{ item }}"
#     state: "present"
#   with_items:
#     - 'urllib3'
#     - 'pyopenssl'
#     - 'ndg-httpsclient'
#     - 'pyasn1'
- name: Cassandra | Update the cassandra host configuration
  become: yes
  template: src=hosts.j2 dest=/etc/hosts


- name: debian | Adding Cassandra Debian Repo Key
  apt_key:
    url: "{{ cassandra_debian_repo_info.repo_key }}"
    state: "present"

- name: debian | Adding Cassandra Debian Repo
  apt_repository:
    repo: "{{ cassandra_debian_repo_info.repo }}"
    state: "present"

- name: debian | Installing Cassandra
  apt:
    name: "cassandra"
    state: "present"

- name: config | Configuring Cassandra
  template:
    src: "cassandra.yaml.j2"
    dest: "{{ cassandra_root_dir }}/cassandra.yaml"
    owner: "root"
    group: "root"
    mode: 0644
  notify: "restart cassandra"
