## Cassandra Provisioning ##
- name: Cassandra | Install required python packages for cassandra snapshotter via apt-get
  become: yes
  action: apt pkg={{ item }} state=present update_cache=yes
  with_items:
    - libffi-dev
    - libssl-dev
    - build-essential
    - python-dev
    - lzop
    - curl
    
- name: Cassandra | Add the datastax repository apt-key
  become: yes
  apt_key:
    url: "http://debian.datastax.com/debian/repo_key"
    state: present
  tags:
    - provision

- name: Cassandra | Add the cassandra 3.7 repository
  become: yes
  apt_repository:
    repo: "deb http://debian.datastax.com/datastax-ddc 3.7 main"
    state: present
  tags:
    - provision

- name: Cassandra | Install the cassandra package
  become: yes
  apt:
    name: cassandra
    state: present
    update_cache: yes
  tags:
    - provision

- name: Cassandra | Update the cassandra configuration
  become: yes
  template:
    src: "cassandra.j2"
    dest: "/etc/cassandra/cassandra.yaml"
    mode: 0644
  tags:
    - provision

- name: Cassandra | Restart cassandra
  become: yes
  service:
    name: cassandra
    state: restarted
  tags:
    - provision
