---
- name: Ensure env directory exists
  file:
    path: /home/deployer/env
    state: directory
    owner: root
    group: root

- name: Ensure stack directory exists
  file:
    path: /home/deployer/stack
    state: directory
    owner: root
    group: root

- name: Ensure config directory exists
  file:
    path: /home/deployer/config
    state: directory
    owner: root
    group: root

- name: Save configurations into an env file
  template: src=jenkins-android-slave.env dest=/home/deployer/env/jenkins-android-slave.env mode=0644

- name: Save stack file
  template: src=stack-jenkins-android-slave.yml dest=/home/deployer/stack/jenkins-android-slave.yml mode=0644

- name: Deploy stack
  shell: "docker stack deploy -c jenkins-android-slave.yml jenkins-android-slave"
  args:
    chdir: /home/deployer/stack
