apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-default
  namespace: {{ .Values.namespace }}
data:
  proxy-default.conf: |
    {{ .Values.proxyconfig | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    {{ .Values.nginxconfig | nindent 4 }}
