apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-nginx-ingress
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-nginx-ingress
  template:
    metadata:
      labels:
        app: public-nginx-ingress
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagepullsecrets }}
      {{- end }}
      {{- if .Values.sunbird_portal_player_cdn_enabled }}
      containers:
      - name: name
        image: "{{ .Values.dockerhub }}/{{ .Values.repository }}:{{ .Values.image_tag }}"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
---
apiVersion: v1
kind: Service
metadata:
  name: public-nginx-ingress
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  selector:
    app: public-nginx-ingress
