- name: copy the template
  template: src=start_balancer.j2 dest=/home/deployer/start_balancer.js mode=0777 

- name: run the template
  become: yes
  command: mongo < /home/deployer/start_balancer.js
