version: '3.1'

services:
  proxy:
    image: "${AUTHOR}/${NAME}:${TAG}"
    ports:
      - "443:443"
      - "80:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.env==${ENV}"
    secrets:
      - source: site.key
        target: site.key
      - source: site.crt
        target: site.crt
    networks:
      - default
      - api-manager_default

secrets:
  site.key:
    file: /tmp/secrets/site.key
  site.crt:
    file: /tmp/secrets/site.crt

networks:
  api-manager_default:
    external: true
  default:
    driver: overlay
