version: '3.1'

services:
  proxy:
    image: "${ORG}/${NAME}:${TAG}"
    ports:
      - "443:443"
      - "80:80"
    deploy:
      replicas: 1
    secrets:
      - site.key
      - site.crt
      - 6668D813A4753B96EA5155091D045060.txt
    networks:
      - default
      - api-manager_default
      - jenkins_default
      - monitor
      - application_default
      - logger_logger

secrets:
  site.key:
    external: true
  site.crt:
    external: true
  6668D813A4753B96EA5155091D045060.txt:
    external: true

networks:
  api-manager_default:
    external: true
  jenkins_default:
    external: true
  monitor:
    external: true
  application_default:
    external: true
  logger_logger:
    external: true
  default:
    driver: overlay
  