redisAddress: redis://{{groups['lp-redis'][0]}}:6379
serviceMonitor:
  # When set true then use a ServiceMonitor to configure scraping
  enabled: true
  labels: # labels with which the prometheus choose the serviceMonitor
    app: monitoring
    release: prometheus-operator
