---
- name: Create the directory
  file: path={{ mongo_backup_dir }} state=directory recurse=yes
  
- set_fact:
    mongo_backup_file_name: "mongo-backup-{{ ansible_hostname }}-{{ lookup('pipe', 'date +%Y-%m-%d') }}"
 
- set_fact:
    mongo_backup_file_path: "{{ mongo_backup_dir }}/{{ mongo_backup_file_name }}"

- name: take dump
  shell: "mongodump --out={{ mongo_backup_file_path }}"
    
- name: Compress the backup file
  shell: "tar -czf {{ mongo_backup_file_path }}.tar.gz {{ mongo_backup_file_path }}"

- name: upload file to azure storage
  include_role:
    name: azure-cloud-storage
    tasks_from: blob-upload.yml
  vars:
    blob_container_name: "{{ mongo_backup_azure_container_name }}"
    container_public_access: "off"
    blob_file_name: "{{ mongo_backup_file_name }}.tar.gz"
    local_file_or_folder_path: "{{ mongo_backup_file_path }}.tar.gz"
    storage_account_name: "{{ azure_management_storage_account_name }}"
    storage_account_key: "{{ azure_management_storage_account_key }}"
  when: cloud_service_provider == "azure"
 
- name: clean up backup dir after upload
  file: path={{ mongo_backup_dir }} state=absent
