- name: dir is created mongo-metadata
  file: path=/mongo-metadata state=directory

- name: Run the mongo command for config
  shell: mongod --configsvr --dbpath /mongo-metadata --port 27019 &
  async: 15
  poll: 0


