- name: install zip
  become: yes
  apt: name=zip state=present

- include: common.yml

- include: config.yml
  when: config is defined

- include: query.yml
  when: query is defined

- include: shard.yml
  when: shard is defined

  
