- name: copy the template add_shards.yml
  template: src=add_shards.j2 dest=/home/deployer/add_shards.js mode=0777 

- name: run the template lock_config
  become: yes
  shell: mongo --host {{mongo.query_ip}} --port 27017 < /home/deployer/add_shards.js
  async: 15
  poll: 0


