version: '3.1'
services:
  opensaber-encryption-service:
    image: "{{hub_org}}/{{image_name}}:{{image_tag}}"
    env_file:
      /home/deployer/env/opensaber-encryption.env
    deploy:
      args:
        DB_PASSWORD: "{{application_postgres_password}}"
      replicas: "{{ encryption_replicas | default(1) }}"
      resources:
        reservations:
          memory: "{{ encryption_reservation_memory  | default('256M') }}"
        limits:
          memory: "{{ encryption_limit_memory  | default('512M') }}"
    networks:
      - application_default
networks:
  application_default:
    external: true

