version: '3.1'

services:
  adminutil:
    image: sunbird/adminutil:{{image_tag}}
    environment:
      SERVER_PORT: {{ adminutil__port }}
      AM_ADMIN_API_ENDPOINT: {{ kong_url }}
      SPRING_PROFILES_ACTIVE: {{ adminutil__spring_profile }}
      DEFAULT_CONSUMER_GROUP: {{ adminutil__default_consumer_group }}
      ENDPOINTS_HEALTH_ID: {{ adminutil__health_id }}
      ENDPOINTS_HEALTH_SENSITIVE: "{{ adminutil__is_health_sensitive }}"
      ENDPOINTS_METRICS_ID: {{ adminutil__metrics_id }}
      ENDPOINTS_METRICS_SENSITIVE: {{ adminutil__is_metrics_sensitive }}
    ports:
      - {{ adminutil__port }}:4000
    networks:
      - application_default
    deploy:
      replicas: 1

networks:
  application_default:
    external: true
