version: '3.1'

services:
  adminutil:
    image: sunbird/adminutil:{{image_tag}}
    volumes:
      - "/home/deployer/env/application.properties:/opt/app/application.properties"
    ports:
      - 4000:4000
    networks:
      - application_default
    deploy:
      replicas: 1

networks:
  application_default:
    external: true
