---
- name: Remove keycloak2 service
  shell: "docker service rm keycloak2"
  ignore_errors: yes

- name: Deploy keycloak2 service
  shell: "docker service create --replicas {{ keycloak2.replicas | default(1) }} -p 8080:8080 --name keycloak2 --hostname keycloak2 --reserve-memory {{ keycloak2.reservation_memory |  default('768M') }} --limit-memory {{ keycloak2.limit_memory |  default('1024M') }}  --network {{ sunbird_network }} --env-file /home/deployer/env/sunbird_keycloak2.env {{hub_org}}/{{image_name}}:{{image_tag}}"
  args:
    chdir: /home/deployer/stack
