---
- name: Kong API
  hosts: kong-api
  roles:
    - {role: kong-api, tags: ['kong-api']}
    - {role: kong-consumer, tags: ['kong-consumer']}

- name: Remote postgres DB
  hosts: kong-remote-postgres-db
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - {role: 'remote-postgresql-db' }
  tags:
    - kong-remote-postgres-db
  become: yes
