---
- hosts: "{{ remote }}"
  become: yes
  roles:
    - ssh-access
  tags:
    - add-user

- hosts: "{{ remote }}"
  become: yes
  tasks:
    - user: name="{{ user }}" state=absent remove=yes
  tags:
    - delete-user