- hosts: swarm-manager
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - stack-proxy
  tags:
    - stack-proxy

- hosts: swarm-manager
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - stack-api-manager
  tags:
    - stack-api-manager

- hosts: swarm-manager
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - stack-sunbird
  tags:
    - stack-sunbird

- hosts: swarm-manager
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - stack-logger
  tags:
    - stack-logger

- hosts: swarm-manager
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - stack-adminutil
  tags:
    - stack-adminutil

- hosts: monitor
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - monitor-config
  tags:
    - stack-monitor
    
- hosts: swarm-manager
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - stack-monitor
  tags:
    - stack-monitor

