- hosts: swarm-bootstrap-manager
  become: yes
  pre_tasks:
    - include_vars: 'secrets/{{env}}.yml'
      ignore_errors: true
  roles:
    - stack-proxy
  tags:
    - stack-proxy

- hosts: swarm-bootstrap-manager
  become: yes
  pre_tasks:
    - include_vars: 'secrets/{{env}}.yml'
      ignore_errors: true
  roles:
    - stack-api-manager
  tags:
    - stack-api-manager

- hosts: swarm-bootstrap-manager
  become: yes
  pre_tasks:
    - include_vars: 'secrets/{{env}}.yml'
      ignore_errors: true
  roles:
    - stack-sunbird
  tags:
    - stack-sunbird

- hosts: swarm-bootstrap-manager
  become: yes
  pre_tasks:
    - include_vars: 'secrets/{{env}}.yml'
      ignore_errors: true
  roles:
    - stack-logger
  tags:
    - stack-logger

- hosts: swarm-bootstrap-manager
  become: yes
  pre_tasks:
    - include_vars: 'secrets/{{env}}.yml'
      ignore_errors: true
  roles:
    - stack-adminutil
  tags:
    - stack-adminutil

- hosts: swarm-bootstrap-manager
  become: yes
  pre_tasks:
    - include_vars: 'secrets/{{env}}.yml'
      ignore_errors: true
  roles:
    - stack-monitor
  tags:
    - stack-monitor

- hosts: swarm-bootstrap-manager
  become: yes
  pre_tasks:
    - include_vars: 'secrets/{{env}}.yml'
      ignore_errors: true
  roles:
    - stack-keycloak
  tags:
    - stack-keycloak1

- hosts: swarm-bootstrap-manager
  become: yes
  pre_tasks:
    - include_vars: 'secrets/{{env}}.yml'
      ignore_errors: true
  roles:
    - stack-keycloak
  tags:
    - stack-keycloak2