- hosts: localhost
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  tasks:
    - name: this block consists of tasks related to azure storage
      block:
        - name: set common azure variables
          set_fact:
            blob_container_name: "{{ desktop_container }}"
            blob_file_name: "{{ destination_path }}"
            blob_container_folder_path: "/{{ destination_path }}"
            local_file_or_folder_path: "{{ playbook_dir }}/../{{ src_file_path }}"
      
        - block:
          - name: upload file to azure storage
            include_role:
              name: azure-cloud-storage
              tasks_from: blob-upload.yml
            vars:
              container_public_access: "container"
              storage_account_name: "{{ azure_public_storage_account_name }}"
              storage_account_key: "{{ azure_public_storage_account_key }}"
          tags:
            - upload-desktop-faq
      
        - block:
          - name: upload file to azure storage
            include_role:
              name: azure-cloud-storage
              tasks_from: blob-upload.yml
            vars:
              container_public_access: "off"
              storage_account_name: "{{ azure_private_storage_account_name }}"
              storage_account_key: "{{ azure_private_storage_account_key }}"
          tags:
            - upload-label
      
        - block:
          - name: upload batch of files to azure storage
            include_role:
              name: azure-cloud-storage
              tasks_from: blob-upload-batch.yml
            vars:
              container_public_access: "container"
              storage_account_name: "{{ azure_public_storage_account_name }}"
              storage_account_key: "{{ azure_public_storage_account_key }}"
          tags:
            - upload-chatbot-config
            - upload-batch
      when: cloud_service_provider == "azure"