- hosts: local
  gather_facts: no
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  tasks:
    - name: Create directories
      file:
        path: dial_schema_template_files/{{ item.path }}
        state: directory
        owner: jenkins
        group: jenkins
      with_filetree: "{{ source_name }}"
      when: item.state == 'directory'

    - name: Template files in all directories
      template:
        src: "{{ item.src }}"
        dest: dial_schema_template_files/{{ item.path }}
      with_filetree: "{{ source_name }}"
      when: item.state == 'file'

    - name: upload batch of files to azure storage
      include_role:
        name: azure-cloud-storage
        tasks_from: blob-upload-batch.yml
      vars:
        blob_container_name: "{{ dial_plugin_container_name }}"
        container_public_access: "blob"
        blob_container_folder_path: "/schemas/local"
        local_file_or_folder_path: "dial_schema_template_files"
        storage_account_name: "{{ azure_public_storage_account_name }}"
        storage_account_key: "{{ azure_public_storage_account_key }}"
      when: cloud_service_provider == "azure"