- hosts: swarm-bootstrap-manager
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  tasks:
    - command: "docker service ls"
  tags:
    - docker-service-list

- hosts: swarm-bootstrap-manager
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  tasks:
    - command: "docker service update {{ docker_swarm_service_name }} --force --detach=false"
  tags:
    - docker-service-restart
