- hosts: swarm-nodes
  become: yes
  gather_facts: no
  tasks:
  - command: docker swarm leave --force

- hosts: swarm-nodes
  become: yes
  gather_facts: no
  tasks:
  - command: docker system prune -af
