- hosts: swarm-nodes
  become: yes
  gather_facts: no
  tasks:
  - command: docker swarm leave --force

- hosts: swarm-nodes
  become: yes
  gather_facts: no
  tasks:
  - command: docker system prune -af

- hosts: swarm-nodes
  become: yes
  gather_facts: no
  tasks:
  - command: reboot
    ignore_errors: True

- hosts: localhost
  become: yes
  gather_facts: no
  tasks:
  - command: sleep 100

- hosts: swarm-nodes
  become: yes
  gather_facts: no
  tasks:
  - command: hostname
