- hosts: swarm-bootstrap-manager
  become: yes
  gather_facts: no
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  tasks:
    - name: "List all services"
      command: "docker service ls"
      register: command_result
    - debug: var=command_result.stdout_lines
  tags:
    - docker-swarm-service-list

- hosts: swarm-bootstrap-manager
  become: yes
  gather_facts: no
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  tasks:
    - name: "Restart service {{ docker_swarm_service_name }}"
      command: "docker service update {{ docker_swarm_service_name }} --force --detach=false"
      register: command_result
    - debug: var=command_result.stdout_lines
  tags:
    - docker-swarm-service-restart
