---
# Redirect requests from opensaber.io/
# to http://opensaber-service:8080
- hosts: swarm-bootstrap-manager
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - nginx-update
  run_once: true
  ignore_errors: true

# Provisioning Encryption service
- hosts: swarm-bootstrap-manager
  become: true
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - encryption

