- hosts: es-backup
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - es-azure-snapshot
  tags:
    - es_backup

- hosts: es-backup
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - es-azure-restore
  tags:
    - es_restore

- hosts: log-es-backup
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - es-azure-snapshot
  tags:
    - log_es_backup

- hosts: log-es-backup
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - es-azure-restore
  tags:
    - log_es_restore

- hosts: log-es
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - es_curator
  tags:
    - purge_old_logs