- hosts: es-backup
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  vars:
    - es_snapshot_host: "{{app_es_snapshot_host}}"
    - snapshot_base_path: "{{app_snapshot_base_path}}"
  roles:
    - role: es-azure-snapshot
      when: cloud_provider == "azure"
    - role: aws-azure-snapshot
      when: cloud_provider == "aws"
    - role: gclou-azure-snapshot
      when: cloud_provider == "gcloud"
    - role: es5-snapshot-purge
  tags:
    - es_backup
  run_once: true

- hosts: log-es-backup
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  vars:
    - es_snapshot_host: "{{log_es_snapshot_host}}"
    - snapshot_base_path: "{{log_snapshot_base_path}}"
  roles:
    - es-azure-snapshot
    - es5-snapshot-purge
  tags:
    - log_es_backup
