- hosts: es-backup
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - es-azure-snapshot
  tags:
    - es_backup

- hosts: es-restore
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - es-azure-restore
  tags:
    - es_restore
