---
- name: Setup Jenkins Master
  hosts: jenkins-master
  vars_files:
    - 'secrets/{{env}}.yml'
  become: yes
  roles:
    - openjdk
    - git
    - jenkins
  tags:
    - jenkins-master

- name: Setup CI proxy
  hosts: ci-proxy
  vars_files:
    - 'secrets/{{env}}.yml'
  become: yes
  roles:
    - role: nginx
      nginx_configs:
        ssl:
          - ssl_certificate_key {{ ci_proxy_nginx_ssl_key_file }}
          - ssl_certificate     {{ ci_proxy_nginx_ssl_cert_file }}
      nginx_sites:
        jenkins:
            - listen {{ ci_proxy_ssl_port }} ssl
            - location /jenkins/ { proxy_pass http://{{ groups['jenkins-master'][0] }}:{{ jenkins_http_port}}{{ jenkins_url_prefix }}/; }
        jenkins_http_redirect:
            - listen 80
            - return 301 https://$server_name$request_uri
    - role: ci-proxy
  tags:
    - ci-proxy
