- hosts: swarm-bootstrap-manager
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - stack-android-jenkins-slave
  tags:
    - android-jenkins-slave

- hosts: swarm-bootstrap-manager
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - stack-jenkins-slave
  tags:
    - jenkins-slave
