- hosts: local
  gather_facts: no
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  tasks:
    - name: upload batch of files to azure storage
      include_role:
        name: azure-cloud-storage
        tasks_from: blob-upload-batch.yml
      vars:
        blob_container_name: "{{ plugin_container_name }}"
        container_public_access: "container"
        blob_container_folder_path: "/schemas/local"
        local_file_or_folder_path: "{{ source_name }}"
        storage_account_name: "{{ azure_public_storage_account_name }}"
        storage_account_key: "{{ azure_public_storage_account_key }}"
      when: cloud_service_provider == "azure"