- hosts: swarm-bootstrap-manager
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - stack-logger
  tags:
    - stack-logger

- hosts: log-forwarder
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - vm-agents-filebeat
  tags:
    - log-forwarder

- hosts: log-es
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  vars:
    es_plugins_reinstall: true
    es_plugins:
      - name: cloud-azure
  roles:
    - openjdk
    - elasticsearch_old
  tags:
    - log-es

