# - hosts: mongo_servers
#   vars:
#     mongo: true
#   become: yes
#   roles: 
#         - mongodb

# - hosts: config_servers
#   vars:
#     config: true
#   become: yes
#   roles: 
#         - mongodb

- hosts: query_servers
  become: yes
  vars:
    query: true
  roles: 
        - mongodb

# - hosts: shard_servers
#   vars:
#     shard: true
#   become: yes
#   roles: 
#         - mongodb
