---
# This Playbook would deploy the whole mongodb cluster with replication and sharding.
- hosts: all
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
  - role: common

- hosts: mongo_servers
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
  - role: mongod

- hosts: mongoc_servers
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
  - role: mongoc

- hosts: mongos_servers
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
  - role: mongos


