- name: Creating prometheus configuration folder
  hosts: swarm-agent-for-prometheus
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  tasks:
    - name: Create prometheus data dir
      file:
        path: "{{ prometheus_mount_point }}"
        state: directory
        mode: 0755
        owner: 'nobody'
        group: 'nogroup'
  tags:
    - swarm-prometheus

- name: Creating prometheus-stateful configuration folder
  hosts: swarm-agent-for-prometheus-stateful
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  tasks:
    - name: Create prometheus data dir
      file:
        path: "{{ prometheus_stateful_mount_point }}"
        state: directory
        mode: 0755
        owner: 'nobody'
        group: 'nogroup'
  tags:
    - prometheus-stateful

- hosts: swarm-agent-dashboard
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  tasks:
    - name: Create grafana data dir
      file: path=/var/dockerdata/grafana state=directory mode=755
    - name: Change ownership
      command: chown -R 472 /var/dockerdata/grafana
  tags:
    - grafana

- hosts: swarm-agent-for-alertmanager
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  tasks:
    - name: Create alertmanager data dir
      file:
        path: /var/dockerdata/alertmanager/data
        state: directory
        mode: 0755
  tags:
    - alertmanager

- hosts: alertmanager_stateful
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  tasks:
    - name: Create alertmanager data dir
      file:
        path: /var/dockerdata/stateful_alertmanager/data
        state: directory
        mode: 0755
  tags:
    - stateful-alertmanager

- hosts: swarm-bootstrap-manager
  gather_facts: false
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  tasks:
    - name: Add label for prometheus node
      shell: "docker node update --label-add prometheus=1 {{ hostvars[groups['swarm-agent-for-prometheus'][0]]['ansible_hostname'] }}"
  tags:
    - swarm-prometheus
  run_once: true

- hosts: swarm-bootstrap-manager
  gather_facts: false
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  tasks:
    - name: Add label for alertmanager node
      shell: "docker node update --label-add alertmanager=1 {{ hostvars[groups['swarm-agent-for-alertmanager'][0]]['ansible_hostname'] }}"
  tags:
    - alertmanager
  run_once: true

- name: labelling grafana
  hosts: swarm-dashboard
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  tasks:
    - name: Add label for grafana node
      command: "docker node update --label-add grafana=1 {{ hostvars[groups['swarm-agent-dashboard'][0]]['ansible_hostname'] }}"
  tags:
    - grafana
  run_once: true

- name: labelling stateful prom
  hosts: swarm-dashboard
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  tasks:
    - name: Adding label for stateful prometheus
      shell: "docker node update --label-add prometheus_stateful=1 {{ hostvars[groups['swarm-agent-for-prometheus-stateful'][0]]['ansible_hostname'] }}"
  tags:
    - prometheus-stateful

- name: labelling statefull alermanager
  hosts: swarm-dashboard
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  tasks:
    - name: Adding label for stateful alertmanager
      shell: "docker node update --label-add alertmanager_stateful=1 {{ hostvars[groups['alertmanager_stateful'][0]]['ansible_hostname'] }}"
  tags:
    - stateful-alertmanager

- hosts: swarm-bootstrap-manager
  gather_facts: false
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  roles:
    - stack-monitor
    - {role: 'monit', monit_checks: ['alertmanager', 'prometheus']}
  tags:
    - swarm-prometheus
  run_once: true

- name: Deploying stateful monitoring
  hosts: swarm-dashboard
  gather_facts: false
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  roles:
    - stack-monitor-stateful
  tags:
    - prometheus-stateful
  run_once: true

- hosts: swarm-dashboard
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  roles:
    - stack-grafana
  tags:
    - grafana
  run_once: true

- hosts: all
  become: yes
  gather_facts: false
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  roles:
    - vm-agents-nodeexporter
  tags:
    - node-exporter
    - lp_dp_monitoring

- hosts: process-exporter
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  roles:
    - vm-agents-processexporter
  tags:
    - process-exporter
    - lp_dp_monitoring

