- hosts: local
  become: yes
  gather_facts: no
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  # The vars: section is added for the below reason
  # 1. Introduce a common variable for various clouds. In case of azure, it refers to container name, in case of aws / gcp, it refers to folder name
  # 2. We want to avoid too many new variable introduction / replacement in first phase. Hence we will reuse the existing variable defined in private repo
  #    or other default files and just assign the value to the newly introduced common variable 
  # 3. After few releases, we will remove the older variables and use only the new variables across the repos
  vars:
    nodebbui_storage: "{{ nodebbui_container_name }}"
  tasks:
    - name: delete files and folders from azure storage using azcopy
      include_role:
        name: azure-cloud-storage
        tasks_from: delete-using-azcopy.yml
      vars:
        blob_container_name: "{{ nodebbui_storage }}"
        blob_container_folder_path: ""
        storage_account_name: "{{ azure_public_storage_account_name }}"
        storage_account_sas_token: "{{ azure_public_storage_account_sas }}"
      when: cloud_service_provider == "azure"

    - name: upload batch of files to azure storage
      include_role:
        name: azure-cloud-storage
        tasks_from: blob-upload-batch.yml
      vars:
        blob_container_name: "{{ nodebbui_storage }}"
        container_public_access: "container"
        blob_container_folder_path: ""
        local_file_or_folder_path: "{{ source_name }}"
        storage_account_name: "{{ azure_public_storage_account_name }}"
        storage_account_key: "{{ azure_public_storage_account_key }}"
      when: cloud_service_provider == "azure"