- hosts: all
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - vm-agents-filebeat
  tags:
    - log-forwarder

- hosts: all
  become: yes
  roles:
    - vm-agents-nodeexporter
  tags:
    - metrics-exporter