- hosts: all
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - vm-agents-filebeat
  tags:
    - log-forwarder

- hosts: all
  roles:
    - role: vm-agents-nodeexporter
      prometheus_node_exporter_file_sd: True
      prometheus_node_exporter_file_sd_locations:
        - { host: prometheus01.in.example.com, path: "/etc/prometheus/endpoints/node-{{ inventory_hostname }}.yml" }
  tags:
    - exporter-node