- hosts: all
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - vm-agents-filebeat
  tags:
    - log-forwarder

- hosts: all
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - vm-agents-nodeexporter
  tags:
    - metrics-exporter