---
- hosts: local
  gather_facts: false
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  tasks:
  - name: this block consists of tasks related to azure storage
    block:
      - name: set common azure variables
        set_fact:
          blob_container_name: "{{ plugin_container_name }}"
          container_public_access: "container"
          blob_delete_pattern: "content-plugins/{{ plugins_name }}"
          blob_container_folder_path: "/content-plugins/{{ plugins_name }}"
          local_file_or_folder_path: "{{ source_file }}"
          storage_account_name: "{{ azure_public_storage_account_name }}"
          storage_account_key: "{{ azure_public_storage_account_key }}"
    
      - name: delete batch of files from azure storage
        include_role:
          name: azure-cloud-storage
          tasks_from: blob-delete-batch.yml
    
      - name: upload batch of files to azure storage
        include_role:
          name: azure-cloud-storage
          tasks_from: blob-upload-batch.yml
    when: cloud_service_provider == "azure"
