- hosts: localhost
  vars:
    ansible_connection: local
    # This variable will be coming from jenkins as extra vars
    databases: "{{ migration_databses.split(',') }}"
  roles:
    - postgres-migration
