- hosts: "dev-mongodb"
  become: yes
  roles:
        - mongodb

- hosts: "dev-cassandra"
  become: yes
  roles:
       - java 
       - cassandra

- hosts: "dev-elasticsearch"
  become: yes
  roles:
        - java
        - elasticsearch
