- hosts: "cassandra"
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
   - java
   - cassandra
  tags:
   - cassandra

- hosts: es
  become: yes
  pre_tasks:
    - name: Install jmespath
      apt: name=python3-jmespath state=present
      become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - openjdk
    - elasticsearch
  tags:
    - es

- hosts: log-es
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - openjdk
    - elasticsearch_old
  tags:
    - log-es

- hosts: postgresql
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  pre_tasks:
    - name: install setfacl support
      become: yes
      apt: pkg=acl
  roles:
    - postgresql
  tags:
    - postgresql
