- hosts: "cassandra"
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
   - java
   - cassandra
  tags:
   - cassandra

- hosts: es
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - openjdk
    - elasticsearch
  tags:
    - es