- hosts: "cassandra"
  become: yes
  pre_tasks:
    - include_vars: 'secrets/{{env}}.yml'
      ignore_errors: true
  roles:
   - cassandra
  tags:
   - cassandra

- hosts: es
  become: yes
  pre_tasks:
    - include_vars: 'secrets/{{env}}.yml'
      ignore_errors: true
  roles:
    - openjdk
    - elasticsearch
  tags:
    - es

- hosts: log-es
  become: yes
  pre_tasks:
    - include_vars: 'secrets/{{env}}.yml'
      ignore_errors: true
  roles:
    - openjdk
    - elasticsearch_old
  tags:
    - log-es

- hosts: postgresql-master
  become: yes
  pre_tasks:
    - include_vars: 'secrets/{{env}}.yml'
      ignore_errors: true
    - name: install setfacl support
      become: yes
      apt: pkg=acl
  roles:
    - postgresql-master
  tags:
    - postgresql-master

- hosts: postgresql-slave
  become: yes
  pre_tasks:
    - include_vars: 'secrets/{{env}}.yml'
      ignore_errors: true
    - name: install setfacl support
      become: yes
      apt: pkg=acl
  roles:
    - postgresql-slave
  tags:
    - postgresql-slave
