- hosts: "dev-cassandra"
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
   - java
   - cassandra

- hosts: es
  become: yes
  vars_files:
    - 'secrets/{{env}}.yml'
  roles:
    - java
    - elasticsearch
  tags:
    - es