- hosts: localhost
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  vars:
    artifacts_container: "{{ blob_container }}"
    artifact_path: "{{ playbook_dir }}/../{{ blob_folder }}"
  environment:
    AZURE_STORAGE_ACCOUNT: "{{ sunbird_public_storage_account_name }}"
    AZURE_STORAGE_KEY: "{{ sunbird_public_storage_account_key }}"
  tasks:
    - name: upload files
      include_role:
        name: upload-batch
      vars:
        artifact: "{{ item }}"
      with_items:
        - "{{ blob_folder.split(',') }}"
  tags:
    - upload-faqs 
