- hosts: localhost
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  tasks:
  - name: template schema files
    template:
      src: "{{ item }}"
      dest: "{{ item }}"
    with_fileglob:
      - "{{ playbook_dir }}/../utils/sunbird-RC/schema/*.json"
  tags:
    - upload-RC-schema

- hosts: localhost
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  tasks:
  - name: upload batch of files to azure storage
    include_role:
      name: azure-cloud-storage
      tasks_from: blob-upload-batch.yml
    vars:
      blob_container_name: "{{ container_name }}"
      container_public_access: "container"
      blob_container_folder_path: ""
      local_file_or_folder_path: "{{ playbook_dir }}/../utils/{{ item }}"
      storage_account_name: "{{ azure_public_storage_account_name }}"
      storage_account_key: "{{ azure_public_storage_account_key }}"
    with_items:
      - "{{ source_folder.split(',') }}"
    when: cloud_service_provider == "azure"
  tags:
    - upload-faqs
    - upload-RC-schema
