---
kong_admin_api_url: "http://localhost:8001"

kong_apis: []
# Example:
# kong_apis:
# - name: "readContent"
#   request_path: "/v3/public/content/read"
#   upstream_url: "{{ learning_service_url }}/v3/public/content/read"
#   strip_request_path: true
#   plugins:
#    - {name: 'jwt'}
#    - {name: 'cors'}
#    - {name: 'statsd', config.metrics: "{{ statsd_metrics }}" }
#    - {name: 'acl', config.whitelist: 'contentUser'}
#    - {name: 'rate-limiting', config.hour: "{{ medium_rate_limit_per_hour }}"}
#    - {name: 'request-size-limiting', config.allowed_payload_size: "{{ medium_request_size_limit }}" }