---
- name: Get the environment name for the artifact name
  shell: "cat {{offline_repo_location}}/offline-installer-repo/src/package.json | jq -r '.name'"
  register: env_name

- name: Display the environment name of the installer
  debug:
    msg: "{{env_name.stdout}}"

- name: Create a variable to inject environment name to upload to azure blob
  set_fact:
    environment_name: "{{ env_name.stdout }}"

- name: Get the version from the package.json file
  shell: "cat {{offline_repo_location}}/offline-installer-repo/src/package.json | jq -r '.version'"
  register: version

- name: Display the version number of the installer
  debug:
    msg: "{{version.stdout}}"

- name: Create a variable to inject version in the template
  set_fact:
    installer_version: "{{ version.stdout }}"

- name: get the directory name
  shell: "ls {{offline_repo_location}}/offline-installer-repo/offline_artifacts/"
  register: folderName

- debug:
    msg: "{{folderName.stdout}}"

- name: set the folder name to copy the artifacts
  set_fact:
    time: "{{folderName.stdout}}"

- name: copy the installer artifacts and metadata files to upload it to azure blob and generate latest.json file
  template:
    src: "{{item}}.j2"
    dest: "{{offline_repo_location}}/offline-installer-repo/{{item}}"
    mode: '0755'
  with_items:
    - artifacts.sh
    - metadata.sh

- name: copy the artifacts and generate the metadata file
  shell: "bash {{offline_repo_location}}/offline-installer-repo/{{item}}"
  args:
    chdir: "{{offline_repo_location}}/offline-installer-repo/"
  with_items:
    - artifacts.sh
    - metadata.sh

- name: this block consists of tasks related to azure storage
  block:
    - name: set common azure variables
      set_fact:
        blob_container_name: "{{ offline_installer_storage }}"
        container_public_access: "blob"
        storage_account_name: "{{ azure_public_storage_account_name }}"
        storage_account_key: "{{ azure_public_storage_account_key }}"

    - name: upload batch of files to azure storage
      include_role:
        name: azure-cloud-storage
        tasks_from: blob-upload-batch.yml
      vars:
        blob_container_folder_path: ""
        local_file_or_folder_path: "{{ offline_repo_location }}/offline-installer-repo/offline_artifacts"
    
    - name: upload batch of files to azure storage
      include_role:
        name: azure-cloud-storage
        tasks_from: blob-upload-batch.yml
      vars:
        blob_container_folder_path: "/latest"
        local_file_or_folder_path: "{{ offline_repo_location }}/offline-installer-repo/offline_artifacts/{{ folderName.stdout }}"
  when: cloud_service_provider == "azure"

- name: Create a zip of the folder to archieve the artifact
  archive:
    path:
    - "{{offline_repo_location}}/offline-installer-repo/offline_artifacts/{{folderName.stdout}}"
    dest: "{{offline_repo_location}}/{{offline_installer_type}}.zip"
    owner: jenkins
    group: jenkins
    format: zip

- name: copy latest.json file to archieve it in jenkins
  copy:
    src: "{{offline_repo_location}}/offline-installer-repo/offline_artifacts/{{folderName.stdout}}/latest.json"
    dest: "{{offline_repo_location}}/latest.json"
    owner: jenkins
    group: jenkins
    remote_src: yes

- name: change the ownership of the directory to jenkins user
  file:
    path: "{{offline_repo_location}}"
    state: directory
    recurse: yes
    owner: jenkins
    group: jenkins