- name: Add group
  group: name={{ group }} state=present
  become: yes

- name:  Create user
  become: yes
  user: state=present name="{{ user }}" group="{{ group }}" groups=sudo shell=/bin/bash createhome=yes password="{{password}}" update_password=always

- name: debug
  become: yes
  debug: var=public_key

- name: Add ssh public key
  authorized_key: user="{{ user }}" key="{{ public_key }}"
  become: yes

- name: Install key
  copy: content="{{ public_key }}" dest=/home/{{ user }}/.ssh/{{ public_key }} mode=600 owner={{ user }}
  become: yes