- name: Copy the templates
  become: yes
  template: src={{item}} dest=/tmp/{{item}}
  with_items:
             - tables_postgres.sql
             
- name: Run the cassandra.cql command
  become: yes
  environment:
    PGPASSWORD: "{{ application_postgres_password }}"
  command: "psql -U {{application_postgres_user}} -d {{application_postgres_database}} -a -f /tmp/tables_postgres.sql"