---
- name: Ensure env directory exists
  file:
    path: /home/deployer/env
    state: directory
    owner: root
    group: root

- name: Ensure stack directory exists
  file:
    path: /home/deployer/stack
    state: directory
    owner: root
    group: root

- name: Ensure config directory exists
  file:
    path: /home/deployer/config
    state: directory
    owner: root
    group: root

- name: Save configurations into an env file
  template: src=jenkins-documentation-slave dest=/home/deployer/env/jenkins-documentation-slave mode=0644

- name: Save stack file
  template: src=stack-jenkins-documentation-slave.yml dest=/home/deployer/stack/jenkins-documentation-slave.yml mode=0644

- name: Deploy stack
  shell: "docker stack deploy -c stack-jenkins-documentation-slave.yml jenkins-documentation-slave"
  args:
    chdir: /home/deployer/stack
