global:
  resolve_timeout: 5m

route:
  receiver: 'slack'
  repeat_interval: 15m
  group_interval: 5m
  group_wait: 1m
  routes:
  - receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        api_url: "{{slack_url}}"
        username: 'Prometheus - Alerter'
        channel: 'monitor_alert'
        text: 'Instances: {{ '{{' }} range .Alerts {{ '}}' }}{{ '{{' }} .Labels.instance {{ '}}' }}{{ '{{' }} end {{ '}}' }}'
        icon_emoji: ':dart:'
