version: '3.1'

services:

  jekyll-jenkins-slave:
    image: sunbird/jekyll-jenkins-swarm-agent:2.5.3
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master ${JENKINS_URL} -labels ${SITE_SLAVE_LABEL} -executors 1 -name site-jenkins-slave
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 1024M
    networks:
      - jenkins_default

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

networks:
  jenkins_default:
    external: true
