############## Admin ######################
core_vault_docker_registry_url: ""
core_vault_docker_registry_user: 
core_vault_docker_registry_password: 

############## LP ######################
lp_vault_azure_storage_secret: 
sunbird_public_storage_account_key: 
lp_vault_graph_passport_key: # can be any random string; to check integrity of content submitted for reviewal
lp_vault_youtube_api_key: 
lp_vault_dial_service_authorization: 
lp_vault_backup_azure_storage_secret: 
lp_vault_artifact_azure_account_key: 

 
### Google drive key ###
auto_creator_gdrive_api_key: 

auto_creator_gservice_acct_cred: 

# CSP vars
cloud_public_storage_secret: 
cloud_private_storage_secret:
cloud_management_storage_secret: 
cloud_artifact_storage_secret: 

