version: '3.1'

services:
  elasticsearch:
    image: elasticsearch
    environment:
      - LOGSPOUT=ignore
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9201:9200'
    networks:
      - logger

  kibana:
    image: kibana
    environment:
      - LOGSPOUT=ignore
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    networks:
      - logger

  logstash:
    image: grvsinghania/logger:0.0.1-bronze
    command: logstash -f /conf/logstash.conf
    environment:
      - LOGSPOUT=ignore
    depends_on:
      - elasticsearch
    networks:
      - logger

  logspout:
    image: gliderlabs/logspout
    command: syslog+tcp://logstash:51415
    deploy:
      mode: global
    environment:
      - SYSLOG_FORMAT=rfc3164
    depends_on:
      - logstash
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    networks:
      - logger
      - api-manager_default
      - jenkins_default
      - monitor
      - application_default
  oauth:
    image: mryu/oauth2-proxy
    command: |
      -cookie-secure=false
      -upstream=http://kibana:5601
      -redirect-url=https://sunbird-1b.centralindia.cloudapp.azure.com/oauth2/callback
      -http-address=oauth:4111
      -email-domain=sahajsoft.com
    environment:
      - OAUTH2_PROXY_CLIENT_ID=`cat /run/secrets/google_client_id`
      - OAUTH2_PROXY_CLIENT_SECRET=`cat /run/secrets/google_client_secret`
      - OAUTH2_PROXY_COOKIE_SECRET=`cat /run/secrets/cookie_secret`
    ports:
      - "4111"
    secrets:
      - google_client_id
      - google_client_secret
      - cookie_secret

networks:
  api-manager_default:
    external: true
  jenkins_default:
    external: true
  monitor:
    external: true
  application_default:
    external: true
  logger:
    driver: overlay

secrets:
  google_client_id:
    external: true
  google_client_secret:
    external: true
  cookie_secret:
    external: true

