version: '3.1'

services:
  elasticsearch:
    image: elasticsearch
    environment:
      - LOGSPOUT=ignore
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9200:9200'
    networks:
      - logger

  kibana:
    image: kibana
    environment:
      - LOGSPOUT=ignore
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    networks:
      - logger

  logstash:
    image: logstash
    command: logstash -f /conf/logstash.conf
    environment:
      - LOGSPOUT=ignore
    depends_on:
      - elasticsearch
    volumes:
      - ./config/logstash.conf:/conf/logstash.conf
    networks:
      - logger

  logspout:
    image: gliderlabs/logspout
    command: syslog+tcp://logstash:51415
    deploy:
      mode: global
    environment:
      - SYSLOG_FORMAT=rfc3164
    depends_on:
      - logstash
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    networks:
      - logger

networks:
  logger:
    driver: overlay

