- name: Add ES repo
  apt_repository: repo='deb [arch=amd64] http://packages.elastic.co/curator/5/debian9 stable main' state=present update_cache=yes

- name: Install elasticsearch curator
  apt: 
    name: elasticsearch-curator=3.4.1-1

- name: Delete old indices 
  shell: curator delete indices --older-than {{ logger_log_retention_days }} --time-unit days --timestring '%Y.%m.%d'
